<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdateChildSupportVerifiedBatch3MaThroughNj extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'MA')->update(['child_support_rules' => "Massachusetts uses income shares model per MGL c.208 § 28. Guidelines calculate support based on combined parental income with percentages: approximately 20% for 1 child, 27% for 2, 32% for 3, 37% for 4, 40% for 5+ children. Support continues until age 18. Courts adjust for parenting time. Source: Massachusetts General Laws Chapter 208."]);
        DB::table('states')->where('state_code', 'MI')->update(['child_support_rules' => "Michigan uses income shares model per MCL 552.605. Percentages based on combined adjusted gross income: 17% for 1 child, 25% for 2, 30% for 3, 35% for 4, 37% for 5+ children. Formula adjusts for parenting time and income exceeding the statutory cap. Child support continues until age 18. Source: MCL 552.605."]);
        DB::table('states')->where('state_code', 'MN')->update(['child_support_rules' => "Minnesota uses income shares model per Minnesota Statutes § 518A.35. Support calculated on combined parental income using tables with adjustment for parenting time. Previous percentage guidelines (25-30%) replaced with detailed income shares calculation. Percentages vary by income level. Medical support required as additional obligation. Source: Minnesota Statutes § 518A.35."]);
        DB::table('states')->where('state_code', 'MS')->update(['child_support_rules' => "Mississippi uses percentage of income model per Mississippi Code § 43-19-101. Guidelines percentages: 14% for 1 child, 20% for 2, 22% for 3, 24% for 4, 26% for 5+ children of adjusted gross yearly income. Guideline applies to individuals with adjusted income between $5,000-$50,000. Source: Mississippi Code § 43-19-101."]);
        DB::table('states')->where('state_code', 'MO')->update(['child_support_rules' => "Missouri uses income shares model per Missouri Revised Statutes § 452.340. Courts apply Missouri Supreme Court guidelines with percentages ranging from 20% for 1 child to 50% for 6+ children of combined income. Joint physical custody may allow 50% reduction from basic amount. Form 14 Schedule of Basic Child Support Obligations contains specific calculations. Source: Missouri Revised Statutes § 452.340."]);
        DB::table('states')->where('state_code', 'MT')->update(['child_support_rules' => "Montana uses income shares model per Montana Code Annotated § 40-4-204. Support calculated using combined parental income with adjustment for parenting time. Specific percentages based on income levels and number of children. Court considers economic impact on obligor and standard of living. Child support continues to age 18. Source: Montana Code Annotated § 40-4-204."]);
        DB::table('states')->where('state_code', 'NE')->update(['child_support_rules' => "Nebraska uses percentage of income model per Nebraska Supreme Court Rules Article 2. Support calculated as percentage of combined parental income with each parent's share determined by their income proportion. Percentages vary by income level. Adjustments for parenting time apply. Medical support separate obligation. Source: Nebraska Revised Statutes § 42-364."]);
        DB::table('states')->where('state_code', 'NV')->update(['child_support_rules' => "Nevada uses tiered income shares model per NAC 425 (effective February 1, 2020). Tiered percentages by income bracket: 16% on income to $6,000, 8% on $6,001-$10,000, 4% on income over $10,000 for 1 child. Higher percentages for multiple children. No automatic cap; uses federal poverty guidelines for low-income cases. Source: Nevada Administrative Code Chapter 425."]);
        DB::table('states')->where('state_code', 'NH')->update(['child_support_rules' => "New Hampshire uses income shares model per New Hampshire RSA 458-C. Guideline percentages: 22% for 1 child, 34% for 2, 42% for 3, 45% for 4+ children of combined net income up to $44,000. Applied to combined net income of both parents with split between parents proportional to their income shares. Adjusted by parenting time. Source: New Hampshire RSA 458-C."]);
        DB::table('states')->where('state_code', 'NJ')->update(['child_support_rules' => "New Jersey uses income shares model with statutory factors per New Jersey Revised Statutes § 2A:34-23. Presumptive guidelines calculated from combined gross income for families with income up to $187,200. Court considers needs of children, standard of living, and both parents' financial circumstances. Above income cap, factors apply. Health insurance and childcare costs additional. Source: New Jersey Revised Statutes § 2A:34-23."]);
    }

    public function down() { }
}
