<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdateSpousalSupportVerifiedBatch1AlThroughGa extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'AL')->update(['spousal_support_rules' => "Alabama awards alimony under Alabama Code § 30-2-51. Court may award rehabilitative or periodic alimony based on need and ability to pay. Duration of periodic alimony not to exceed length of marriage unless marriage is 20+ years (no limit). Rehabilitative alimony limited to 5 years except in extraordinary circumstances. No formula for amount; courts consider earning capacity, financial condition, age, health, contributions, and other statutory factors. Alimony terminates upon death or remarriage. Source: Alabama Code § 30-2-51 et seq."]);
        DB::table('states')->where('state_code', 'AK')->update(['spousal_support_rules' => "Alaska awards spousal support under Alaska Statutes § 25.24.160. Court may award temporary, rehabilitative, or reorientation support. Court has broad discretion; no formula for calculation. Awards may be lump sum or installments for limited or unlimited period. Courts consider length of marriage, earning capacity, financial situation, conduct of parties, and other relevant factors. Support terminates upon death or remarriage. Source: Alaska Statutes § 25.24.160."]);
        DB::table('states')->where('state_code', 'AZ')->update(['spousal_support_rules' => "Arizona awards spousal support (maintenance) under Arizona Revised Statutes § 25-319. Court may award for period necessary to enable recipient to achieve self-sufficiency. Arizona Supreme Court Spousal Maintenance Guidelines (effective June 30, 2023) set amount and duration ranges based on marriage length and income. Duration ranges from 0% for short marriages to longer terms for longer marriages. No deviation from duration ranges authorized. Source: Arizona Revised Statutes § 25-319."]);
        DB::table('states')->where('state_code', 'AR')->update(['spousal_support_rules' => "Arkansas awards alimony under Arkansas Code § 9-12-312. Court may award rehabilitative alimony in fixed installments for specified period. No formula; judges have broad discretion in determining whether support is appropriate and amount. Alimony automatically terminates upon earliest of: remarriage of recipient, establishment of intimate cohabiting relationship, or change in circumstances. Contributions to education/earning capacity considered. Source: Arkansas Code § 9-12-312."]);
        DB::table('states')->where('state_code', 'CA')->update(['spousal_support_rules' => "California awards spousal support under Family Code § 4320 and related sections. For short-term marriages (under 10 years): presumptive duration is one-half the marriage length. Long-term marriages (10+ years): may receive indefinite support. Amount determined by court considering 14 statutory factors including earning capacity, standard of living, financial ability to pay, and other circumstances. Temporary and permanent support authorized. Source: California Family Code § 4320-4336."]);
        DB::table('states')->where('state_code', 'CO')->update(['spousal_support_rules' => "Colorado awards spousal maintenance under Colorado Revised Statutes § 14-10-114. Advisory guidelines apply to marriages 3-20 years with combined income under $240,000. Duration determined by multiplier: 31% of marriage length at 3 years, increasing 0.165% monthly, capping at 50% (or one-half marriage length). For 20+ year marriages, court may award indefinite term. Guidelines are advisory only. Source: Colorado Revised Statutes § 14-10-114."]);
        DB::table('states')->where('state_code', 'CT')->update(['spousal_support_rules' => "Connecticut awards alimony under Connecticut General Statutes § 46b-82. No formula; judges have broad discretion. Court considers length of marriage, age/health, occupation, earning capacity, education, financial resources, contributions to education/earning capacity, and other relevant factors. Permanent alimony requires specific written basis. Alimony terminates upon death or remarriage unless ordered otherwise. Court may modify for substantial change in circumstances. Source: Connecticut General Statutes § 46b-82."]);
        DB::table('states')->where('state_code', 'DE')->update(['spousal_support_rules' => "Delaware awards alimony under Delaware Code Title 13 § 1512. Eligible party must be dependent and lack sufficient property for own needs. Duration not to exceed 50% of marriage length unless marriage is 20+ years (no time limit). Court determines amount and duration as just, considering financial resources, education/training time needed, standard of living, contributions to earning capacity, and ability to pay. Alimony terminates upon death, remarriage, or cohabitation. Source: Delaware Code Title 13 § 1512."]);
        DB::table('states')->where('state_code', 'FL')->update(['spousal_support_rules' => "Florida awards alimony under Florida Statutes § 61.08 (amended 2023). Durational alimony duration: 50% of short-term marriage (under 10 years), 60% of moderate-term (10-20 years), 75% of long-term (20+ years). Amount cannot exceed 35% of difference between parties' net incomes or recipient's reasonable need, whichever is less. Permanent alimony eliminated effective July 1, 2023. Alimony terminates upon death or remarriage. Effective 2023 for cases filed after July 1. Source: Florida Statutes § 61.08."]);
        DB::table('states')->where('state_code', 'GA')->update(['spousal_support_rules' => "Georgia awards alimony under Georgia Code § 19-6-1. Court may award temporary or permanent alimony. No formula for calculation; judges have broad discretion. Before award, judge must find need and ability to pay. Court considers time needed to acquire training/employment, contributions to marriage, financial condition of both parties, and other factors. Temporary alimony during divorce proceedings; permanent may continue. Alimony terminates upon death. Source: Georgia Code § 19-6-1 et seq."]);
    }

    public function down() { }
}
