<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdateChildSupportVerifiedBatch5SdThroughWy extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'SD')->update(['child_support_rules' => "South Dakota uses income shares model per SDCL 25-7-6. Child support calculated on combined gross income with adjustment for parenting time. Percentages vary by income level and number of children. Court may deviate for special circumstances, unusual needs, extraordinary expenses, or other relevant factors. Medical support separate obligation. Support continues until age 18. Source: South Dakota Codified Laws § 25-7-6."]);
        DB::table('states')->where('state_code', 'TN')->update(['child_support_rules' => "Tennessee uses income shares model per Tennessee Code Annotated § 36-5-101. Child support calculated from combined adjusted gross income using guidelines table. Percentages based on number of children and income level. Court adjusts for parenting time and substantial differences in income. Medical insurance and childcare costs additional obligations. Support continues until age 18 or graduation. Source: TCA § 36-5-101."]);
        DB::table('states')->where('state_code', 'TX')->update(['child_support_rules' => "Texas uses percentage of obligor's income model per Texas Family Code § 154.125. For one child: 20% of net monthly income; two children: 25%; three: 30%; four: 35%; five: 40%; six+: not less than 40%. Income cap adjusted annually. Court adjusts for parenting time and other factors. Child support continues until age 18. Source: Texas Family Code Title 5."]);
        DB::table('states')->where('state_code', 'UT')->update(['child_support_rules' => "Utah uses income shares model per Utah Code § 30-3-34.1. Child support guideline schedule based on combined adjusted gross income and number of children. Specific percentages applied through formula with parenting time adjustment. Court may deviate for special circumstances, ability to pay, and other factors. Support continues until age 18 or high school graduation, whichever is later. Source: Utah Code § 30-3-34.1."]);
        DB::table('states')->where('state_code', 'VT')->update(['child_support_rules' => "Vermont uses income shares model per Vermont Statutes Title 15 § 653. Child support calculated using guidelines table based on combined parental income and number of children. Adjusted for parenting time percentage. Court may deviate for unusual needs, extraordinary expenses, or other relevant factors. Medical and childcare support additional. Support continues until age 18. Source: Vermont Statutes § 15-653."]);
        DB::table('states')->where('state_code', 'VA')->update(['child_support_rules' => "Virginia uses income shares model per Virginia Code § 20-108.2. Child support calculated from combined income using guidelines table. Specific percentages (17%-35% depending on number of children) applied to combined income up to cap. Court adjusts for parenting time and other circumstances. Medical insurance required. Support continues until age 19. Source: Virginia Code § 20-108.2."]);
        DB::table('states')->where('state_code', 'WA')->update(['child_support_rules' => "Washington uses income shares model per Washington RCW 26.19.020. Basic child support obligation calculated on combined parental income up to $5,000/month (adjusted for inflation). Percentages: 17% for 1 child, 25% for 2, 32% for 3, 36% for 4, 40% for 5+ children. Adjusted by parenting time. Support continues until age 18. Source: Washington RCW § 26.19.020."]);
        DB::table('states')->where('state_code', 'WV')->update(['child_support_rules' => "West Virginia uses income shares model per West Virginia Code § 48-13-1. Child support guidelines calculated using combined adjusted gross income of both parents. Specific percentages determined from guidelines table based on income and number of children. Court may deviate for extraordinary circumstances, health insurance costs, and childcare. Support continues to age 18. Source: West Virginia Code § 48-13-1."]);
        DB::table('states')->where('state_code', 'WI')->update(['child_support_rules' => "Wisconsin uses income shares model per Wisconsin Statutes § 767.511. Child support calculated as combined child support obligation then divided by each parent's income percentage. Specific percentages range 17-34% depending on number of children and income. Adjusted for parenting time (more than 25%). Support continues until age 18 or graduation. Source: Wisconsin Statutes § 767.511."]);
        DB::table('states')->where('state_code', 'WY')->update(['child_support_rules' => "Wyoming uses income shares model per Wyoming Statutes § 20-2-304. Child support guidelines table based on combined monthly income and number of children. Percentages vary by income bracket with typical range of 20-36.8%. Obligor parent adjusts for parenting time. Court may deviate for extraordinary circumstances and special needs. Support continues until age 18. Source: Wyoming Statutes § 20-2-304."]);
    }

    public function down() { }
}
