<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdateChildSupportVerifiedBatch4NcThroughSc extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'NC')->update(['child_support_rules' => "North Carolina uses income shares model per NC General Statutes § 50-13.4. Courts apply Conference of Chief District Judges presumptive guidelines. Support based on combined parental income and number of children. The calculation includes each party's income, daycare expenses, medical insurance costs, and children's living arrangements. Courts may deviate from guidelines for good cause. Child support continues until age 18. Source: NC General Statutes § 50-13.4."]);
        DB::table('states')->where('state_code', 'ND')->update(['child_support_rules' => "North Dakota uses income shares guidelines per ND Cen Code Chapter 75-02-04.1. Child support guidelines established by state child support department with effective date July 1, 2023. Amount calculated based on combined monthly net income of both parents with adjustment for parenting time and number of children. Court must follow presumptive guideline amount unless deviation justified. Source: North Dakota Cen Code § 14-09-09.3."]);
        DB::table('states')->where('state_code', 'NM')->update(['child_support_rules' => "New Mexico uses income shares model per NMSA 1978 § 40-4-11.1. Child support guidelines calculated using combined income of both parents. Presumption that 40% of paying parent's gross income for single child support obligation constitutes substantial hardship. Basic obligation calculated based on income shares then divided proportionally. Income cap applies. Source: New Mexico Statutes § 40-4-11.1."]);
        DB::table('states')->where('state_code', 'NY')->update(['child_support_rules' => "New York uses CSSA (Child Support Standards Act) per Family Court Act § 413 and Domestic Relations Law § 240. Percentage of combined income applied up to $183,000 cap (adjusted annually). Percentages: 17% for 1 child, 25% for 2, 29% for 3, 31% for 4, 35% for 5+ children. Support continues until age 21. Guideline is rebuttable presumption. Source: New York Family Court Act § 413."]);
        DB::table('states')->where('state_code', 'OH')->update(['child_support_rules' => "Ohio uses income shares model per Ohio Revised Code § 3119.01. Basic child support schedule created by Director of Job and Family Services applies to combined gross income. Income levels range from $8,400 to $300,000+. Percentages vary by number of children and income level. Automatic 10% reduction for parents with 90+ overnights annually per ORC § 3119.02. Source: Ohio Revised Code Chapter 3119."]);
        DB::table('states')->where('state_code', 'OK')->update(['child_support_rules' => "Oklahoma uses percentage of combined gross income model per Oklahoma Statutes § 43-118. Child Support Guideline Schedule per § 43-119 shows percentages by combined income and number of children. Maximum guideline income set at $15,000/month; additional amounts for higher income determined by court. Both income shares and percentage models used. Source: Oklahoma Statutes Title 43 § 118-119."]);
        DB::table('states')->where('state_code', 'OR')->update(['child_support_rules' => "Oregon uses income shares formula per Oregon Revised Statutes § 25.275. Calculation determined by Oregon Administrative Rules 137-050 sections. Basic obligation based on adjusted incomes and parenting time percentage. Courts adjust for unusual needs and expenses. Oregon Child Support Guidelines Calculator available from Department of Justice. Source: Oregon Revised Statutes § 25.275."]);
        DB::table('states')->where('state_code', 'PA')->update(['child_support_rules' => "Pennsylvania uses income shares model per Title 23 Consolidated Statutes § 4322. Basic child support obligation determined from schedule in Rule 1910.16-3 of Rules of Civil Procedure. Assumes 30% time with obligor parent. Income shares framework with detailed guidelines schedule. Court considers reasonable needs and ability to provide support. Source: Pennsylvania Title 23 § 4322."]);
        DB::table('states')->where('state_code', 'RI')->update(['child_support_rules' => "Rhode Island uses income shares model per Rhode Island General Laws § 15-5-16.2. Guidelines administrative order establishes amounts based on combined income levels and number of children. Income Shares Model calculates what children would receive if parents lived together. Child support continues through age 18. Health insurance and childcare costs additional. Source: Rhode Island General Laws § 15-5-16.2."]);
        DB::table('states')->where('state_code', 'SC')->update(['child_support_rules' => "South Carolina uses income shares model per South Carolina Code § 20-3-160. Guidelines table shows basic support obligation based on parents' combined monthly income and number of children. Obligation divided between parents in proportion to their income percentages. Effective 2024 guidelines updated. Court may deviate for good cause. Source: South Carolina Code § 20-3-160."]);
    }

    public function down() { }
}
