<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdateDivorceProcessVerifiedBatch3MaThroughNj extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'MA')->update(['divorce_process' => "Massachusetts divorce is filed in family court. One spouse must have resided in Massachusetts for at least 1 year before filing (MGL c.208 § 1). There is a mandatory 6-month waiting period from filing before the divorce can be approved. Massachusetts allows no-fault divorce based on irretrievable breakdown. Both parties must either agree on terms or the court determines issues. Source: Massachusetts General Laws Chapter 208."]);
        DB::table('states')->where('state_code', 'MI')->update(['divorce_process' => "Michigan divorce is filed in circuit court. One spouse must reside in Michigan for 180 days and in the county for 10 days before filing (MCL 552.9). There is a mandatory 60-day waiting period without minor children or 6 months with minor children (MCL 552.9f). Michigan allows no-fault divorce based on irretrievable breakdown. Property is divided equitably and custody determined by best interests of child. Source: MCL 552.9, 552.9f."]);
        DB::table('states')->where('state_code', 'MN')->update(['divorce_process' => "Minnesota divorce is filed in district court. One spouse must reside in Minnesota for 180 days before filing (Minnesota Statutes § 518.07). There is no mandatory waiting period after filing. Minnesota allows no-fault divorce based on irretrievable breakdown. Both parties must reach agreement or court determines custody, support, and property division. Grounds include irretrievable breakdown. Source: Minnesota Statutes § 518.07."]);
        DB::table('states')->where('state_code', 'MS')->update(['divorce_process' => "Mississippi divorce is filed in circuit or chancery court. One spouse must reside in Mississippi for 6 months before filing (Mississippi Code § 93-5-5). There is a mandatory 60-day waiting period after filing before the court hears the case. Mississippi allows no-fault divorce based on irreconcilable differences. Courts determine property division and custody. Source: Mississippi Code § 93-5-5."]);
        DB::table('states')->where('state_code', 'MO')->update(['divorce_process' => "Missouri divorce is filed in circuit court. One spouse must reside in Missouri for 90 days before filing (Missouri Revised Statutes § 452.305). There is a mandatory 30-day waiting period from filing before judgment can be entered. Missouri allows no-fault divorce based on irretrievable breakdown. Property is divided equitably and custody is determined by best interests of child. Source: Missouri Revised Statutes § 452.305."]);
        DB::table('states')->where('state_code', 'MT')->update(['divorce_process' => "Montana divorce is filed in district court. One spouse must reside in Montana for 90 days before filing. Children must have resided in Montana for 6 months (Montana Code Annotated § 40-4-104). There is a mandatory 20-day waiting period from filing (MCA 40-4-107). Montana allows no-fault dissolution based on irretrievable breakdown. Both parties must reach agreement or court determines custody, support, and property division. Source: MCA 40-4-104, 40-4-107."]);
        DB::table('states')->where('state_code', 'NE')->update(['divorce_process' => "Nebraska divorce is filed in district court. One spouse must reside in Nebraska for 1 year before filing (Nebraska Revised Statutes § 42-349). There is a mandatory 60-day waiting period after service of process before hearing (Nebraska Revised Statutes § 42-363). Nebraska allows no-fault divorce based on irretrievable breakdown. Both parties must reach agreement or court determines custody, support, and property division. Source: Nebraska Revised Statutes § 42-349, 42-363."]);
        DB::table('states')->where('state_code', 'NV')->update(['divorce_process' => "Nevada divorce is filed in district court. One spouse must reside in Nevada for 6 weeks before filing and provide residency affidavit (Nevada Revised Statutes § 125.020). Nevada has no mandatory waiting period - divorces can proceed immediately once residency is met. Nevada allows no-fault divorce. Both parties must reach agreement on all issues or court determines them. Source: Nevada Revised Statutes § 125.020."]);
        DB::table('states')->where('state_code', 'NH')->update(['divorce_process' => "New Hampshire divorce is filed in family division of circuit court. One spouse must reside in New Hampshire for 1 year before filing, or grounds for divorce must have occurred in-state with one spouse still residing there (New Hampshire RSA 458:5). There is no mandatory waiting period. New Hampshire allows both fault and no-fault divorce based on irreconcilable differences. Courts determine custody, support, and property division. Source: New Hampshire RSA 458:5."]);
        DB::table('states')->where('state_code', 'NJ')->update(['divorce_process' => "New Jersey divorce is filed in family court. One spouse must reside in New Jersey for 1 year before filing, except in adultery cases (New Jersey Revised Statutes § 2A:34-10). There is no standard mandatory waiting period. New Jersey allows both fault and no-fault divorce. Both parties must reach agreement or court determines custody, support, and property division. Grounds for no-fault divorce include irreconcilable differences. Source: New Jersey Revised Statutes § 2A:34-10."]);
    }

    public function down() { }
}
