<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdateCustodyVerifiedBatch3MaThroughNj extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'MA')->update(['custody_of_child' => "Massachusetts uses temporary shared legal custody presumption with no presumption for permanent joint custody. Courts determine custody based on best interests of child considering multiple factors. Shared custody plans required when contested. Both parents have equal custody rights initially (MGL c.208 § 31). Courts encourage parental involvement but are not bound by joint custody presumption. Source: MGL c.208 § 31."]);
        DB::table('states')->where('state_code', 'MI')->update(['custody_of_child' => "Michigan presumes equal or approximately equal parenting time is in child's best interest. Courts favor joint custody arrangements (MCL 722.21). Statutory factors include child's needs, parent relationships, ability to provide care, stability, domestic violence, and child's preferences. Both parents' involvement encouraged unless contrary to child's best interest. Source: MCL 722.21-722.31."]);
        DB::table('states')->where('state_code', 'MN')->update(['custody_of_child' => "Minnesota presumes joint legal custody is in child's best interest per Minnesota Statutes § 518.17. Courts consider child's needs, parent relationships, stability, domestic violence history, and child's preferences. Exception: rebuttable presumption against joint custody if domestic abuse documented. Both parents encouraged to stay involved. Source: Minnesota Statutes § 518.17."]);
        DB::table('states')->where('state_code', 'MS')->update(['custody_of_child' => "Mississippi presumes joint custody is in child's best interest when both parents agree per Mississippi Code § 93-5-24. Courts consider child's needs, parent relationships, stability, domestic violence, and child's preferences. Rebuttable presumption against sole custody if parent has family violence history. No presumption favoring mothers. Source: Mississippi Code § 93-5-24."]);
        DB::table('states')->where('state_code', 'MO')->update(['custody_of_child' => "Missouri presumes equal or approximately equal parenting time is in child's best interest per Missouri Revised Statutes § 452.375. Courts must consider joint physical and joint legal custody unless one parent opposes without legitimate cause. Best interests factors include child's needs, parent relationships, stability, domestic violence. Non-discriminatory custody standards. Source: Missouri Revised Statutes § 452.375."]);
        DB::table('states')->where('state_code', 'MT')->update(['custody_of_child' => "Montana courts determine parenting plan based on best interests of child per Montana Code Annotated § 40-4-212. Courts favor frequent and continuing contact with both parents unless detrimental to child. Factors include child's needs, parent relationships, stability, continuity of care, domestic violence, and child's wishes. Both parents encouraged to stay involved. Source: Montana Code Annotated § 40-4-212."]);
        DB::table('states')->where('state_code', 'NE')->update(['custody_of_child' => "Nebraska places custody based on best interests of child per Nebraska Revised Statutes § 42-364. Courts may award joint custody when in child's best interest or when both parents agree. Equal custody rights between both mothers and fathers. Factors include child's relationship with each parent, child's wishes, child's health and welfare. Both parents' involvement encouraged. Source: Nebraska Revised Statutes § 42-364."]);
        DB::table('states')->where('state_code', 'NV')->update(['custody_of_child' => "Nevada presumes joint physical custody is in child's best interest per Nevada Revised Statutes § 125C.0035. Courts must state reasons if denying joint custody request. Sole consideration is best interests of child. Factors include child's wishes if old enough, parent ability to provide care, frequency of parent contact, and domestic violence. Both parents encouraged to stay involved. Source: Nevada Revised Statutes § 125C.003, 125C.0035."]);
        DB::table('states')->where('state_code', 'NH')->update(['custody_of_child' => "New Hampshire presumes joint decision-making responsibility is in child's best interest per New Hampshire RSA 461-A. Courts consider parent relationships, child's needs, continuity of care, parenting schedule preferences, and domestic violence history. No presumption against equal parenting time without compelling reason. Both parents' involvement encouraged unless detrimental. Source: New Hampshire RSA 461-A:6."]);
        DB::table('states')->where('state_code', 'NJ')->update(['custody_of_child' => "New Jersey awards custody based on best interests of child per New Jersey Revised Statutes § 9:2-4. Public policy favors frequent and continuing contact with both parents. Statutory factors include parents' ability to agree, willingness to accept custody, child's needs, stability of home, domestic violence history, and child's preferences. Custody not denied solely for one parent's opposition to shared arrangement. Source: New Jersey Revised Statutes § 9:2-4."]);
    }

    public function down() { }
}
