<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdatePropertyDivisionVerifiedBatch4NcThroughSc extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'NC')->update(['property_division' => "North Carolina is equitable distribution state per NC Gen Stat § 50-20. Court divides marital property fairly but not necessarily equally. Separate property includes assets owned before marriage, inherited, and gifted property. Courts consider length of marriage, financial condition, contributions to property acquisition, earning capacity, and other factors. Equitable division is just allocation. Source: NC General Statutes § 50-20."]);
        DB::table('states')->where('state_code', 'ND')->update(['property_division' => "North Dakota is equitable distribution state per North Dakota Century Code § 14-16-08. Court divides marital property equitably. Separate property includes property owned before marriage, inherited, and received as gifts. Courts consider length of marriage, financial condition, contributions to acquisition, earning capacity, and ability to acquire future property. Equitable is fair but not necessarily equal. Source: North Dakota Century Code § 14-16-08."]);
        DB::table('states')->where('state_code', 'NM')->update(['property_division' => "New Mexico is equitable distribution state per New Mexico Statutes § 40-3-8. Court divides marital property equitably considering value, duration of marriage, contribution of each spouse to property acquisition, and child custody impact. Separate property (before marriage, inherited, gifted) not divided. Property acquired by labor during marriage is marital property. Source: New Mexico Statutes § 40-3-8."]);
        DB::table('states')->where('state_code', 'NY')->update(['property_division' => "New York is equitable distribution state per Domestic Relations Law § 236. Marital property divided equitably between spouses. Property acquired during marriage presumed marital property. Separate property includes property owned before marriage, inherited, and gifted. Courts consider length of marriage, financial condition, contribution to property acquisition, earning capacity, and custodial parental role. Source: New York Domestic Relations Law § 236."]);
        DB::table('states')->where('state_code', 'OH')->update(['property_division' => "Ohio is equitable distribution state per Ohio Revised Code § 3105.17. Court divides marital property equitably but not necessarily equally. Separate property includes property owned before marriage, inherited, and gifted. Courts consider length of marriage, financial condition, contributions to property acquisition, earning capacity, and other factors. Marital property includes retirement accounts and benefits earned during marriage. Source: Ohio Revised Code § 3105.17."]);
        DB::table('states')->where('state_code', 'OK')->update(['property_division' => "Oklahoma is equitable distribution state per Oklahoma Statutes § 43-121. Court divides marital property in manner deemed just and equitable. Separate property includes assets owned before marriage, inherited property, and gifts to one spouse. Courts consider financial condition, income, contributions to property, earning capacity, length of marriage, and other factors. Equitable division is fair allocation. Source: Oklahoma Statutes § 43-121."]);
        DB::table('states')->where('state_code', 'OR')->update(['property_division' => "Oregon is equitable distribution state per Oregon Revised Statutes § 107.135. Court divides marital property equitably. Separate property (owned before marriage, inherited, gifted, property agreement designated separate) not divided. Courts consider length of marriage, financial condition, contributions to property acquisition, earning capacity, and tax consequences. Property acquired during marriage is presumed marital property. Source: Oregon Revised Statutes § 107.135."]);
        DB::table('states')->where('state_code', 'PA')->update(['property_division' => "Pennsylvania is equitable distribution state per Title 23 § 3501. Court divides marital property equitably. Separate property includes property owned before marriage, inherited, and gifted. Pennsylvania considers each spouse's contribution (financial and nonfinancial including homemaking), length of marriage, standard of living, earning capacity, ability to support self after divorce. Marital property broadly defined to include most assets. Source: Pennsylvania Title 23 § 3501."]);
        DB::table('states')->where('state_code', 'RI')->update(['property_division' => "Rhode Island is equitable distribution state per Rhode Island General Laws § 15-5-16.1. Court divides marital property equitably between spouses. Separate property includes property owned before marriage, inherited, and by written agreement designated separate. Courts consider length of marriage, financial condition, contribution to acquisition, earning capacity, age/health, and child custody. Equitable distribution is fair but not necessarily equal. Source: Rhode Island General Laws § 15-5-16.1."]);
        DB::table('states')->where('state_code', 'SC')->update(['property_division' => "South Carolina is equitable distribution state per South Carolina Code § 20-3-160. Court divides marital property equitably. Separate property (before marriage, inherited, gifted, by agreement) not divided. Courts consider length of marriage, financial condition of each party, contribution to acquisition and preservation of property, earning capacity, and child custody arrangements. Equitable division is just and equitable allocation. Source: South Carolina Code § 20-3-160."]);
    }

    public function down() { }
}
