<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdateMediationSupportVerifiedBatch2HiThroughMd extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'HI')->update(['mediation_support' => "Hawaii strongly encourages mediation for family law matters under Hawaii Statutes § 658-1 et seq. Mediation available by agreement or court order for any dispute. Not mandatory statewide but encouraged. Court may refer cases to mediation. Parties may hire certified mediators or use court-connected program. Costs typically shared equally. Mediation is confidential under state law. Family Court facilitators also available for assistance. Source: Hawaii Statutes § 658-1."]);
        DB::table('states')->where('state_code', 'ID')->update(['mediation_support' => "Idaho encourages mediation in family law cases under Idaho Rules of Civil Procedure. Mediation available by agreement or court order. Not mandatory but recommended for contested issues. Parties may hire certified mediators. Costs agreed upon by parties. Court may order mediation at any time. Mediation communications confidential. Court-connected mediation programs available in some districts. Source: Idaho Rules of Civil Procedure."]);
        DB::table('states')->where('state_code', 'IL')->update(['mediation_support' => "Illinois encourages mediation in family law disputes through Illinois Code of Civil Procedure § 2-601. Mediation available by agreement or court order. Not mandatory statewide. Court may refer any case to mediation. Certified mediators available through court programs. Costs paid by agreement or mediator fees shared equally. Mediation communications privileged and confidential. Illinois courts promote alternatives to litigation. Source: Illinois Code of Civil Procedure § 2-601."]);
        DB::table('states')->where('state_code', 'IN')->update(['mediation_support' => "Indiana encourages mediation in family law matters under Indiana Rules of Trial Procedure. Mediation available by agreement or court order. Court may refer cases for mediation. Not mandatory statewide. Certified family law mediators available. Parties share costs equally unless agreed otherwise. Mediation is confidential under state law. Court retains authority to resolve unresolved issues. Source: Indiana Rules of Trial Procedure."]);
        DB::table('states')->where('state_code', 'IA')->update(['mediation_support' => "Iowa encourages mediation in family law cases under Iowa Code § 598.21. Mediation available by agreement or court referral. Not mandatory statewide. Court may order mediation for child-related issues or all contested matters. Parties pay mediator costs or split equally. Certified mediators available. Mediation communications confidential under state law. Court-connected programs available in many counties. Source: Iowa Code § 598.21."]);
        DB::table('states')->where('state_code', 'KS')->update(['mediation_support' => "Kansas encourages mediation in family law disputes through Kansas Statutes § 23-606. Mediation available by agreement or court order. Not mandatory but recommended. Court may refer cases to mediation at any stage. Certified mediators available through Kansas mediation program. Costs typically shared by parties. Mediation communications privileged and confidential. Good faith participation expected. Source: Kansas Statutes § 23-606."]);
        DB::table('states')->where('state_code', 'KY')->update(['mediation_support' => "Kentucky encourages mediation in family law cases through Kentucky Revised Statutes § 421.570. Mediation available by agreement or court order. Not mandatory statewide. Court may refer child custody and visitation disputes to mediation. Parties may hire certified mediators. Costs agreed upon by parties. Mediation confidential and inadmissible in court. Court retains final authority on unresolved issues. Source: Kentucky Revised Statutes § 421.570."]);
        DB::table('states')->where('state_code', 'LA')->update(['mediation_support' => "Louisiana encourages mediation through Louisiana Code of Civil Procedure Article 1121 et seq. Mediation available by agreement or court order. Court may order mediation for any civil matter including family disputes. Not mandatory but available upon request. Parties may hire mediators or use court services. Costs determined by agreement. Mediation communications confidential. Court may enforce mediation agreements. Source: Louisiana Code of Civil Procedure Article 1121."]);
        DB::table('states')->where('state_code', 'ME')->update(['mediation_support' => "Maine requires mediation for child custody disputes under Maine Statutes Title 19-A § 751. Court-ordered mediation before contested custody hearing unless waived by agreement. Free or low-cost court-connected mediation available. Private mediators may be used. Mediators must be qualified and trained. Mediation is confidential under Maine law. Parties must participate in good faith. Court may sanction non-compliance. Source: Maine Statutes Title 19-A § 751."]);
        DB::table('states')->where('state_code', 'MD')->update(['mediation_support' => "Maryland encourages mediation in family law cases through Maryland Code Family Law § 3-704. Mediation available by agreement or court order. Court may order mediation for custody and visitation disputes. Not mandatory statewide. Certified mediators available through court system. Parties share costs or each hire private mediators. Mediation communications confidential under state law. Court retains authority over unresolved issues. Source: Maryland Code Family Law § 3-704."]);
    }

    public function down() { }
}
