<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class PopulateCustodyOfChildInStatesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $states = [
            'AL' => "In Alabama, custody determinations are based on the best interests of the child. The courts consider factors including each parent's ability to provide care, the child's relationship with each parent, the child's health and development needs, and the stability of the home environment. Alabama courts favor joint custody arrangements when both parents are fit and willing to share custody responsibilities. Physical custody refers to where the child lives, while legal custody determines who makes important decisions about education, healthcare, and religious upbringing. The court may award sole custody to one parent if it's determined to be in the child's best interest.",
            'AK' => "Alaska courts determine custody based on what is in the best interests of the child. The state recognizes both joint and sole custody arrangements. Alaska law allows courts to consider factors such as the child's wishes (depending on age and maturity), each parent's emotional bonds with the child, the quality of each parent's relationship with the child, and stability and continuity in the child's life. Alaska strongly encourages parents to develop parenting plans that work for both parties. If parents cannot agree, the court will make custody decisions designed to ensure the child's physical health, mental and emotional well-being, and overall welfare.",
            'AZ' => "Arizona law presumes that joint custody is generally in the best interests of the child, provided both parents are willing and able to share custody. The state distinguishes between legal custody (decision-making authority) and physical custody (where the child resides). Arizona courts consider factors including the wishes of the parents, the wishes of the child, the interaction between the child and parents and siblings, the child's adjustment to home, school, and community, and mental and physical health of all parties. Courts in Arizona aim to maximize each parent's involvement in the child's life while ensuring the child's best interests are protected.",
            'AR' => "Arkansas courts make custody determinations based on the best interests of the child standard. The state permits joint custody, sole custody, and various custodial arrangements. Factors considered include the parent's ability to provide love, affection, and guidance, the child's need for stability and continuity, the length of time the child has lived in a stable home, the child's adjustment to home, school, and community, and the quality of the relationship between the child and each parent. Arkansas encourages parents to cooperate in creating a parenting plan that serves the child's needs. The court will award custody in a manner that maximizes the child's contact with both parents when appropriate.",
            'CA' => "California law favors joint custody and presumes both parents should be involved in raising the child, unless there is evidence of domestic violence or abuse. The state requires courts to consider numerous factors including the health, safety, and welfare of the child, the nature and amount of contact with each parent, and the ability of each parent to provide care. California courts make a distinction between legal custody (decision-making) and physical custody (living arrangements). Parents are encouraged to create parenting plans and share custody arrangements. If parents cannot agree, the court will determine custody based on what serves the child's best interests.",
            'CO' => "Colorado courts make custody decisions based on the best interests of the child. The state encourages joint custody and shared parenting arrangements when both parents are capable and willing. Colorado law considers factors such as the child's wishes, the wishes of each parent, the interaction between the child and family members, the child's adjustment to home and school, and the mental and physical health of all involved. Colorado courts recognize both legal custody (decision-making) and physical custody (residential time). Parenting plans are preferred to ensure clarity about custody, visitation, and decision-making responsibilities.",
            'CT' => "Connecticut courts determine custody based on the best interests of the child. The state encourages joint custody and shared parenting when both parents are willing and able to cooperate. Connecticut considers factors including the desires and preferences of the child, the ability of each parent to provide stability and care, the length and strength of the parent-child relationship, and the adjustment of the child to home, school, and community. Connecticut law emphasizes that both parents should remain involved in important decisions affecting the child's education, healthcare, and religion. The court aims to promote meaningful contact between the child and each parent.",
            'DE' => "Delaware courts determine child custody based on the best interests of the child standard. The state permits joint custody, sole custody, and various shared arrangements. Factors considered include the child's wishes (if of sufficient age and intelligence), each parent's willingness to foster a relationship with the other parent, the stability of the home environment, and the ability of each parent to provide care and supervision. Delaware law encourages parents to develop parenting agreements and share in the raising of their children. If parents cannot agree, the court will make custody determinations that promote the child's welfare and maximize the child's contact with both parents.",
            'FL' => "Florida law encourages shared parental responsibility and joint custody arrangements in most cases. The state presumes that frequent contact with both parents is in the child's best interest. Florida courts consider factors including the love and affection between the child and each parent, the child's adjustment to home and school, the capability of each parent to provide care, and the willingness of each parent to facilitate a relationship with the other parent. Florida requires parents to submit a parenting plan that addresses custody, visitation, and decision-making. The court aims to ensure that both parents play significant roles in the child's life.",
            'GA' => "Georgia courts make custody decisions based on the best interests of the child. The state does not presume that joint custody is automatically appropriate but considers each case individually. Georgia law allows courts to consider the child's preference, the mental and physical health of the parties, the adjustment of the child to home and school, and each parent's ability to provide care and affection. Georgia distinguishes between custody of the person (where the child lives) and custody of the estate (financial matters). The court will award custody in a manner that promotes the child's welfare and allows the child to maintain relationships with both parents.",
            'HI' => "Hawaii courts determine custody based on the best interests of the child. The state recognizes joint custody arrangements and encourages parents to share responsibilities for raising their children. Hawaii law considers factors including the wishes of the parents and the child, the ability of each parent to provide care and supervision, the stability of the home environment, and the child's need for continuity and stability. Hawaii courts examine the parent-child relationships and interactions. The state encourages parents to develop parenting plans and cooperate in child-rearing. If parents dispute custody, the court will make decisions designed to serve the child's welfare.",
            'ID' => "Idaho courts determine custody based on the best interests of the child. The state permits joint custody and encourages parents to cooperate in parenting. Idaho law considers factors including the child's wishes, the wishes of the parents, the interaction between the child and parents, the child's adjustment to home and school, and the mental and physical health of all parties. Idaho courts recognize the importance of both parents in the child's life. Custody can be awarded as sole custody to one parent or joint custody shared between both parents. The court aims to promote the child's welfare and maintain relationships with both parents.",
            'IL' => "Illinois courts make custody determinations based on the best interests of the child. The state encourages joint custody and shared parenting when both parents are capable and willing. Illinois law considers factors including the child's wishes and preferences, the adjustment of the child to home and school, the willingness of each parent to facilitate a relationship with the other parent, and the mental and physical health of all parties. Illinois courts may order joint legal custody, sole legal custody, joint physical custody, or a combination of arrangements. The goal is to ensure the child has frequent contact with both parents and a stable living environment.",
            'IN' => "Indiana courts determine custody based on the best interests of the child. The state permits joint custody and encourages both parents to be involved in raising their children. Indiana law considers factors including the wishes of the parents and child, the child's adjustment to home and school, the interaction between the child and family members, and the stability of the home environment. Indiana courts recognize that both parents should ideally play significant roles in the child's life. Custody decisions must focus on promoting the child's welfare. If the parents cannot agree on custody, the court will make determinations to serve the child's best interests.",
            'IA' => "Iowa courts make custody decisions based on the best interests of the child. The state encourages joint custody and shared parenting arrangements when both parents are able and willing. Iowa law considers factors including the child's wishes, each parent's ability to provide care, the stability of the home environment, and the child's relationship with siblings and other family members. Iowa courts evaluate the mental and physical health of all parties and the quality of parent-child interactions. Joint custody is an option when both parents can cooperate effectively. If parents cannot agree, the court will award custody in a manner that promotes the child's health, safety, and welfare.",
            'KS' => "Kansas courts determine custody based on the best interests of the child. The state allows both joint custody and sole custody arrangements. Kansas law considers factors including the preferences of the parents and child, the ability of each parent to provide care and guidance, the stability of the home environment, and the child's adjustment to home, school, and community. Kansas courts examine each parent's willingness to encourage and permit contact with the other parent. The court aims to ensure the child has meaningful relationships with both parents when appropriate. Custody decisions focus on promoting the child's physical, mental, and emotional well-being.",
            'KY' => "Kentucky courts make custody determinations based on the best interests of the child. The state permits joint custody and encourages parental cooperation. Kentucky law requires courts to consider factors including the wishes of the parties, the adjustment of the child, the interaction between the child and parents, and the mental and physical health of all parties. Kentucky courts also consider the stability of home and school environments. Both joint custody and sole custody arrangements are available. The court will award custody in a manner that promotes the child's welfare and allows the child to maintain relationships with both parents.",
            'LA' => "Louisiana courts determine custody based on the best interests of the child. Louisiana law favors joint custody arrangements when both parents are willing and able to cooperate. Louisiana considers factors including the child's wishes (depending on age), the stability of the home environment, each parent's involvement in the child's life, and the quality of the parent-child relationships. Louisiana courts examine the mental and physical health of all parties. Joint custody can include joint physical custody and joint legal custody. If joint custody is not feasible, the court will award sole custody to one parent while maintaining the child's relationship with the other parent.",
            'ME' => "Maine courts make custody decisions based on the best interests of the child. The state encourages parental cooperation and shared custody arrangements. Maine law considers factors including the child's wishes and preferences, each parent's ability to provide care and supervision, the stability of the home environment, and the adjustment of the child to home, school, and community. Maine courts examine the parent-child relationships and interactions. The court recognizes the importance of maintaining the child's relationship with both parents. Custody can be awarded as sole custody or joint custody. Maine focuses on arrangements that serve the child's physical health, mental and emotional development, and overall welfare.",
            'MD' => "Maryland courts determine custody based on the best interests of the child. The state permits joint custody and encourages parents to share parenting responsibilities. Maryland law considers factors including the child's wishes, the ability of each parent to care for the child, the stability and permanence of the home environment, and the relationships between the child and parents. Maryland courts examine whether each parent is willing to share custody and encourage the child's relationship with the other parent. Joint custody is an option when both parents can cooperate effectively. The court awards custody in a manner that promotes the child's welfare.",
            'MA' => "Massachusetts courts make custody decisions based on the best interests of the child. The state encourages joint custody and recognizes the value of both parents in the child's life. Massachusetts law requires courts to consider the child's wishes, the stability and permanence of the home environment, the quality of parent-child relationships, and the adjustment of the child to home, school, and community. Massachusetts courts also consider the mental and physical health of all parties. Both joint legal custody and joint physical custody are options. The court aims to ensure maximum meaningful contact with both parents while protecting the child's welfare.",
            'MI' => "Michigan courts determine custody based on the best interests of the child using a statutory framework. The state permits joint custody and encourages parental cooperation. Michigan law requires consideration of factors including the child's wishes, the love and affection between the child and parents, the ability of each parent to provide care, and the stability of the home environment. Michigan courts examine the willingness of each parent to encourage and allow contact with the other parent. Joint custody is preferred when both parents can cooperate. The court will award custody in a manner that promotes the child's physical and mental well-being and maintains relationships with both parents.",
            'MN' => "Minnesota courts make custody determinations based on the best interests of the child. The state encourages joint custody and recognizes the value of both parents' involvement. Minnesota law considers factors including the child's wishes, the ability of each parent to provide care and supervision, the stability of the home environment, and the interaction between the child and family members. Minnesota courts examine each parent's willingness to encourage and facilitate contact with the other parent. Joint legal custody and joint physical custody are preferred options. The court aims to ensure the child has frequent contact with both parents and a stable living arrangement.",
            'MS' => "Mississippi courts determine custody based on the best interests of the child. The state permits joint custody arrangements when both parents are willing and able to cooperate. Mississippi law considers factors including the child's wishes, the stability of the home environment, the ability of each parent to provide care, and the quality of parent-child relationships. Mississippi courts examine the mental and physical health of all parties. Joint custody can provide shared decision-making and shared physical custody. If joint custody is not feasible, the court will award sole custody while working to maintain the child's relationship with both parents.",
            'MO' => "Missouri courts make custody decisions based on the best interests of the child. The state allows joint custody and sole custody arrangements. Missouri law requires consideration of factors including the child's wishes and preferences, the ability of each parent to provide care and guidance, the stability and permanence of the home environment, and the child's adjustment to home, school, and community. Missouri courts examine the quality of parent-child interactions. Both parents' willingness to encourage the child's relationship with the other parent is important. The court will award custody that promotes the child's physical and mental health.",
            'MT' => "Montana courts determine custody based on the best interests of the child. The state encourages joint custody and parental cooperation. Montana law considers factors including the child's wishes, the stability of the home environment, each parent's ability to provide care and supervision, and the adjustment of the child. Montana courts examine the interaction between the child and parents and family members. The court considers whether each parent is willing to encourage and facilitate a relationship with the other parent. Joint custody is an option when both parents can cooperate effectively. The court aims to promote the child's welfare.",
            'NE' => "Nebraska courts make custody determinations based on the best interests of the child. The state permits joint custody arrangements. Nebraska law requires consideration of factors including the child's wishes and preferences, the stability of the home environment, the ability of each parent to provide care, and the quality of parent-child relationships. Nebraska courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is preferred when both parents can cooperate. The court will award custody in a manner that serves the child's welfare.",
            'NV' => "Nevada courts determine custody based on the best interests of the child. The state presumes that joint custody is generally in the child's best interest. Nevada law requires consideration of factors including the child's wishes and preferences, the ability of each parent to provide care and guidance, the stability of the home environment, and the adjustment of the child to home, school, and community. Nevada courts examine the mental and physical health of all parties. Joint custody is preferred unless there is evidence that it would be detrimental to the child. The court will award custody that promotes the child's physical and mental well-being.",
            'NH' => "New Hampshire courts make custody decisions based on the best interests of the child. The state encourages joint custody and recognizes the value of both parents. New Hampshire law considers factors including the child's wishes and preferences, the stability and permanence of the home environment, the relationship between the child and parents, and the adjustment of the child to home, school, and community. New Hampshire courts examine the ability of each parent to provide care and the mental and physical health of all parties. Joint custody is an option when both parents can cooperate effectively. The court aims to ensure maximum contact with both parents.",
            'NJ' => "New Jersey courts determine custody based on the best interests of the child. The state encourages joint custody and shared parenting arrangements. New Jersey law requires consideration of factors including the child's wishes and preferences, the stability of the home environment, each parent's ability to provide care, and the interaction between the child and parents. New Jersey courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is preferred when both parents are capable and willing to cooperate. The court will promote the child's welfare.",
            'NM' => "New Mexico courts make custody determinations based on the best interests of the child. The state permits joint custody and encourages parents to share parenting responsibilities. New Mexico law considers factors including the child's wishes, the stability of the home environment, the ability of each parent to provide care and guidance, and the quality of parent-child relationships. New Mexico courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is an option when both parents can cooperate effectively. The court will award custody promoting the child's welfare.",
            'NY' => "New York courts determine custody based on the best interests of the child. The state permits joint custody and recognizes the importance of both parents. New York law requires consideration of factors including the child's wishes and preferences, the stability of the home environment, the ability of each parent to provide care and guidance, and the adjustment of the child to home, school, and community. New York courts examine the mental and physical health of all parties. Both joint and sole custody arrangements are available. The court considers the willingness of each parent to encourage the child's relationship with the other parent. The goal is to promote the child's welfare.",
            'NC' => "North Carolina courts make custody decisions based on the best interests of the child. The state uses a comprehensive list of factors to determine custody. North Carolina law considers the child's wishes and preferences, the stability of the home environment, each parent's ability to provide care, and the quality of parent-child relationships. North Carolina courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is an option when both parents can cooperate. The court will award custody that serves the child's best interests.",
            'ND' => "North Dakota courts determine custody based on the best interests of the child. The state encourages joint custody and parental cooperation. North Dakota law requires consideration of factors including the child's wishes, the stability of the home environment, each parent's ability to provide care and supervision, and the quality of parent-child relationships. North Dakota courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is preferred when both parents are able and willing to cooperate effectively. The court will award custody promoting the child's welfare.",
            'OH' => "Ohio courts make custody determinations based on the best interests of the child using specific statutory factors. The state encourages joint custody arrangements. Ohio law requires consideration of factors including the child's wishes and preferences, the stability of the home environment, the ability of each parent to provide care, and the interaction between the child and parents. Ohio courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is an option when both parents can cooperate effectively. The court will promote the child's welfare.",
            'OK' => "Oklahoma courts determine custody based on the best interests of the child. The state permits both joint custody and sole custody arrangements. Oklahoma law requires consideration of factors including the child's wishes and preferences, the stability of the home environment, the ability of each parent to provide care and guidance, and the quality of parent-child relationships. Oklahoma courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is an option when both parents can cooperate. The court will award custody that serves the child's best interests.",
            'OR' => "Oregon courts make custody decisions based on the best interests of the child. The state encourages joint custody and recognizes the value of both parents. Oregon law requires consideration of factors including the child's wishes and preferences, the stability of the home environment, the ability of each parent to provide care and supervision, and the adjustment of the child to home, school, and community. Oregon courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is preferred when both parents can cooperate effectively. The court will promote the child's welfare.",
            'PA' => "Pennsylvania courts determine custody based on the best interests of the child using specific statutory factors. The state encourages joint custody arrangements. Pennsylvania law requires consideration of factors including the child's wishes and preferences, the stability of the home environment, the ability of each parent to provide care, and the quality of parent-child relationships. Pennsylvania courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is an option when both parents are capable and willing to cooperate. The court will award custody promoting the child's welfare.",
            'RI' => "Rhode Island courts make custody determinations based on the best interests of the child. The state encourages parental cooperation and shared custody arrangements. Rhode Island law requires consideration of factors including the child's wishes and preferences, the stability of the home environment, the ability of each parent to provide care and guidance, and the quality of parent-child relationships. Rhode Island courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is an option when both parents can cooperate effectively. The court will promote the child's welfare.",
            'SC' => "South Carolina courts determine custody based on the best interests of the child. The state permits both joint custody and sole custody arrangements. South Carolina law requires consideration of factors including the child's wishes and preferences, the stability of the home environment, the ability of each parent to provide care and guidance, and the quality of parent-child relationships. South Carolina courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is an option when both parents are willing and able to cooperate. The court will award custody that serves the child's welfare.",
            'SD' => "South Dakota courts make custody decisions based on the best interests of the child. The state encourages joint custody and recognizes the value of both parents. South Dakota law requires consideration of factors including the child's wishes and preferences, the stability of the home environment, the ability of each parent to provide care and supervision, and the quality of parent-child relationships. South Dakota courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is preferred when both parents can cooperate effectively. The court will promote the child's welfare.",
            'TN' => "Tennessee courts determine custody based on the best interests of the child. The state permits joint custody arrangements. Tennessee law requires consideration of factors including the child's wishes and preferences, the stability of the home environment, the ability of each parent to provide care and guidance, and the quality of parent-child relationships. Tennessee courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is an option when both parents can cooperate effectively. The court will award custody that serves the child's best interests.",
            'TX' => "Texas courts make custody determinations based on the best interests of the child. The state uses the term 'conservatorship' and 'possession' rather than traditional custody. Texas law requires consideration of factors including the child's wishes and preferences, the stability of the home environment, the ability of each parent to provide care and guidance, and the quality of parent-child relationships. Texas courts examine the mental and physical health of all parties. Joint managing conservatorship is an option when both parents are capable and willing to cooperate. The court will award custody that serves the child's welfare.",
            'UT' => "Utah courts determine custody based on the best interests of the child. The state encourages joint custody and parental cooperation. Utah law requires consideration of factors including the child's wishes and preferences, the ability of each parent to provide care and guidance, the stability of the home environment, and the quality of parent-child relationships. Utah courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is preferred when both parents can cooperate effectively. The court will award custody promoting the child's welfare.",
            'VT' => "Vermont courts make custody decisions based on the best interests of the child. The state encourages joint custody and recognizes the value of both parents. Vermont law requires consideration of factors including the child's wishes and preferences, the stability of the home environment, the ability of each parent to provide care and supervision, and the quality of parent-child relationships. Vermont courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is an option when both parents can cooperate effectively. The court will promote the child's welfare.",
            'VA' => "Virginia courts determine custody based on the best interests of the child. The state permits both joint custody and sole custody arrangements. Virginia law requires consideration of factors including the child's wishes and preferences, the stability of the home environment, the ability of each parent to provide care and guidance, and the quality of parent-child relationships. Virginia courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is an option when both parents are capable and willing to cooperate. The court will award custody that serves the child's interests.",
            'WA' => "Washington courts make custody determinations based on the best interests of the child. The state encourages parental cooperation and shared parenting arrangements. Washington law requires consideration of factors including the child's wishes and preferences, the stability of the home environment, the ability of each parent to provide care and guidance, and the quality of parent-child relationships. Washington courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is preferred when both parents can cooperate effectively. The court will promote the child's welfare.",
            'WV' => "West Virginia courts determine custody based on the best interests of the child. The state permits both joint custody and sole custody arrangements. West Virginia law requires consideration of factors including the child's wishes and preferences, the stability of the home environment, the ability of each parent to provide care and guidance, and the quality of parent-child relationships. West Virginia courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is an option when both parents can cooperate effectively. The court will award custody that serves the child's interests.",
            'WI' => "Wisconsin courts make custody decisions based on the best interests of the child. The state encourages joint custody and recognizes the value of both parents. Wisconsin law requires consideration of factors including the child's wishes and preferences, the stability of the home environment, the ability of each parent to provide care and supervision, and the quality of parent-child relationships. Wisconsin courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is preferred when both parents can cooperate effectively. The court will promote the child's welfare.",
            'WY' => "Wyoming courts determine custody based on the best interests of the child. The state permits both joint custody and sole custody arrangements. Wyoming law requires consideration of factors including the child's wishes and preferences, the stability of the home environment, the ability of each parent to provide care and guidance, and the quality of parent-child relationships. Wyoming courts examine the mental and physical health of all parties. The court considers the willingness of each parent to encourage a relationship with the other parent. Joint custody is an option when both parents are capable and willing to cooperate. The court will award custody that serves the child's interests.",
        ];

        foreach ($states as $code => $custody) {
            DB::table('states')
                ->where('state_code', $code)
                ->update(['custody_of_child' => $custody]);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        DB::table('states')->update(['custody_of_child' => null]);
    }
}
