<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class PopulateDivorceProcessInStatesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $states = [
            'AL' => "The divorce process in Alabama begins with filing a petition in the county district court where you reside. You'll need to serve your spouse with the divorce papers and wait for their response. Alabama requires a 30-day waiting period after filing before the divorce can be finalized. In uncontested divorces where both parties agree, the process typically takes 30-60 days after the waiting period expires. The court will review your settlement agreement on property division, custody, and support. Once approved, the judge signs the final divorce decree.",
            'AK' => "Alaska allows residents with just 30 days of residency to file for divorce. File your petition in the district court of the judicial district where you live. Your spouse must be served with the divorce papers. Alaska does not have a mandatory waiting period for uncontested divorces. You can file for a divorce and, if both parties agree on all terms, it can be finalized relatively quickly. The court reviews your settlement agreement and, once approved, issues the final decree of dissolution of marriage.",
            'AZ' => "Arizona's divorce process begins with filing a petition for dissolution of marriage in the superior court. You must meet the 90-day residency requirement. After filing, your spouse is served and has 20 days to respond. Arizona does not impose a mandatory waiting period. In uncontested cases where both parties agree on all issues, the divorce can be finalized within weeks. The court approves the joint dissolution agreement, and the judge signs the decree.",
            'AR' => "To file for divorce in Arkansas, file a complaint in the circuit court of your county. Arkansas requires only 60 days of residency. You must serve your spouse with the divorce papers. There is no mandatory waiting period for uncontested divorces. After filing and serving, if both parties agree on terms, you can reach a settlement relatively quickly. The judge reviews the marital settlement agreement and, if everything is in order, signs the divorce decree.",
            'CA' => "California divorces begin with filing a petition for dissolution of marriage in the superior court. You must have lived in California for six months. After filing, your spouse is served and can respond within 30 days. California has a mandatory six-month waiting period from filing to final judgment. During this time, you negotiate settlement terms. In uncontested cases, once the waiting period ends and agreements are reached, the judge signs the final divorce decree.",
            'CO' => "File a petition for dissolution of marriage in the district court. Colorado requires 90 days of residency. Your spouse must be served with the petition. Colorado does not mandate a waiting period for uncontested divorces. Once both parties agree on all issues, you can submit a joint decree for the judge's approval. The court reviews the settlement and enters the final divorce decree.",
            'CT' => "Connecticut requires one year of residency before filing for dissolution of marriage. File your complaint in the family court of your district. You must serve your spouse with the papers. Connecticut does not require a waiting period. Once filed, if both parties agree on all terms including property division and custody, you can move forward with your settlement agreement. The judge reviews and approves the decree.",
            'DE' => "Delaware has one of the shortest residency requirements at just six days. File your complaint for divorce in the family court. Your spouse must be served with the complaint. Delaware does not have a mandatory waiting period for uncontested divorces. If both parties agree on all terms, the process can move quickly. The court approves the settlement agreement and issues the final divorce decree.",
            'FL' => "File a petition for dissolution of marriage in the circuit court. Florida requires six months of residency. Your spouse must be served with the petition. Florida does not mandate a waiting period for uncontested divorces if both parties have signed a marital settlement agreement. Once the agreement is complete and signed, you can submit it to the court for approval. The judge signs the final judgment of dissolution.",
            'GA' => "File your complaint for divorce in the superior court of your county. Georgia requires six months of residency. Your spouse is served and has 30 days to respond. Georgia does not require a waiting period. If both parties agree on all terms, you can reach a settlement agreement. The court approves the joint agreement, and the judge issues the final divorce decree.",
            'HI' => "File a petition for divorce in the family court. Hawaii requires six months of residency in the islands. Your spouse must be served. Hawaii does not impose a mandatory waiting period for uncontested divorces. Once both parties agree on all issues and sign a settlement agreement, you can submit the documents to court. The judge reviews and signs the final divorce decree.",
            'ID' => "File a complaint for divorce in the district court. Idaho requires six months of residency. Your spouse must be served with the complaint. Idaho does not require a waiting period for uncontested divorces. Once you reach a marital settlement agreement, you can file it with the court. The judge reviews the agreement and issues the final decree of divorce.",
            'IL' => "File a petition for dissolution of marriage in the circuit court. Illinois requires 90 days of residency. Your spouse is served and can respond within 30 days. Illinois does not mandate a waiting period for uncontested divorces with a marital settlement agreement. Once both parties agree on all terms, the court can enter the final judgment of dissolution.",
            'IN' => "File a petition in the circuit or superior court. Indiana requires six months of residency. Your spouse is served with the petition. Indiana requires a minimum of 60 days from filing before the divorce can be finalized. In uncontested cases where both parties agree, you can meet the waiting period and finalize once the agreement is approved by the court.",
            'IA' => "File a petition for dissolution of marriage in the district court. Iowa requires one year of residency. Your spouse is served and can respond. Iowa has a 90-day waiting period after filing before a divorce can be finalized. During this time, you negotiate and reach a settlement agreement. After the waiting period, if all terms are agreed upon, the court enters the final decree.",
            'KS' => "File a petition in the district court. Kansas requires 60 days of residency. Your spouse must be served. Kansas does not require a waiting period for divorce. If both parties agree on all issues, you can file a joint settlement agreement. The court reviews and approves the agreement, and the judge signs the final decree.",
            'KY' => "File a petition for dissolution of marriage in the district or circuit court. Kentucky requires six months of residency. Your spouse is served with the petition. Kentucky requires a 60-day waiting period from filing. After this period, if the parties have reached a settlement agreement, the court can enter the final judgment of dissolution.",
            'LA' => "File a petition for divorce in the district court. Louisiana requires six months of residency. Your spouse is served. Louisiana has unique divorce laws. For uncontested divorces, if both parties agree, you can file a joint petition. The court reviews the agreement and can enter judgment without a waiting period if all terms are agreed upon.",
            'ME' => "File a complaint for divorce in the district court. Maine requires six months of residency. Your spouse is served with the complaint. Maine does not require a waiting period for uncontested divorces. If both parties agree on all issues, you can submit your settlement agreement to the court. The judge reviews and approves the decree.",
            'MD' => "File a complaint for divorce in the circuit court. Maryland requires six months of residency. Your spouse is served. For uncontested divorces with mutual consent, there is no waiting period. Once both parties agree on all terms and sign the settlement agreement, you can file it with the court for the judge's approval and signature.",
            'MA' => "File a complaint in the family and probate court. Massachusetts requires six months of residency. Your spouse is served with the complaint. If both parties agree, you can file a joint petition for divorce without a waiting period. You submit your joint settlement agreement to the court, and the judge approves and signs the judgment of divorce.",
            'MI' => "File a complaint for divorce in the circuit court. Michigan requires six months of residency. Your spouse is served and can respond. Michigan does not have a mandatory waiting period for uncontested divorces. Once both parties agree on all issues, you can submit your judgment of divorce for the court to enter.",
            'MN' => "File a petition for dissolution of marriage in the district court. Minnesota requires six months of residency. Your spouse is served. Minnesota has a 120-day minimum period from service to finalization. During this time, you can negotiate and reach a settlement. Once agreements are reached and the minimum period passes, the court enters the final judgment.",
            'MS' => "File a complaint in the circuit court. Mississippi requires six months of residency. Your spouse is served with the complaint. Mississippi requires a 30-day waiting period. After serving your spouse and waiting 30 days, if both parties agree on all issues, you can file your settlement agreement for the court to approve.",
            'MO' => "Missouri requires only 30 days of residency. File a petition for divorce in the circuit court. Your spouse is served with the petition. Missouri has a 30-day waiting period after filing. If both parties agree on all terms during or after this waiting period, you can submit your settlement agreement. The court approves and enters the final decree.",
            'MT' => "File a petition for dissolution of marriage in the district court. Montana requires six months of residency. Your spouse is served with the petition. Montana does not require a waiting period for uncontested divorces. If both parties agree on all issues, you can file your decree of dissolution for the judge to sign.",
            'NE' => "File a petition for divorce in the district court. Nebraska requires one year of residency. Your spouse is served. Nebraska requires a 120-day waiting period from filing before the divorce can be finalized. During this time, you negotiate settlement terms. After the waiting period, if agreements are reached, the court enters the final decree.",
            'NV' => "File a complaint for divorce in the district court. Nevada requires six months of residency. Your spouse is served with the complaint. Nevada requires a six-month waiting period from service to finalization. Once both parties agree on all terms and the waiting period expires, the court can enter the final judgment of divorce.",
            'NH' => "File a petition in the family division of the circuit court. New Hampshire requires six months of residency. Your spouse is served with the petition. New Hampshire does not require a waiting period. If both parties agree on all issues, you can file your joint settlement agreement. The court approves and enters the final decree.",
            'NJ' => "File a complaint for divorce in the family division. New Jersey requires one year of residency. Your spouse is served. For uncontested cases with a marital settlement agreement, New Jersey does not require a waiting period. You can file your settlement agreement with the court, and the judge approves and signs the judgment of divorce.",
            'NM' => "File a petition for dissolution of marriage in the district court. New Mexico requires six months of residency. Your spouse is served. New Mexico requires a 30-day waiting period after service. After this period, if both parties agree on all terms, you can file your final judgment for the judge to sign.",
            'NY' => "File a summons and complaint in the supreme court. New York requires six months of residency. Your spouse must be served. For uncontested divorces with a separation agreement, New York does not require a waiting period. Once both parties have agreed and signed all documents, the court can enter the judgment of divorce.",
            'NC' => "File a complaint for divorce in the district court. North Carolina requires six months of residency. Your spouse is served. North Carolina requires a six-month separation period before filing or a 30-day period after filing. Once the separation period is satisfied, you can file your settlement agreement for the court to approve.",
            'ND' => "File a complaint for divorce in the district court. North Dakota requires six months of residency. Your spouse is served with the complaint. North Dakota requires a 30-day waiting period after service. Once this period expires and both parties agree on all terms, the court can enter the final judgment of divorce.",
            'OH' => "File a complaint in the domestic relations court. Ohio requires six months of residency. Your spouse is served with the complaint. Ohio does not require a waiting period for uncontested divorces with a separation agreement. Once both parties agree on all issues, you can file your agreed judgment, and the court approves it.",
            'OK' => "File a petition for divorce in the district court. Oklahoma requires six months of residency. Your spouse is served with the petition. Oklahoma requires a 10-day waiting period after service. After this period, if both parties have agreed on all terms, you can file your final judgment for the judge to sign.",
            'OR' => "File a petition for dissolution of marriage in the circuit court. Oregon requires six months of residency. Your spouse is served. Oregon requires a 30-day waiting period from service. After this period, if both parties agree on all terms, you can file your stipulated judgment to be entered by the court.",
            'PA' => "File a complaint in the court of common pleas. Pennsylvania requires six months of residency. Your spouse is served. For uncontested divorces with mutual consent and agreement, there is no mandatory waiting period. You can file your affidavit of consent and settlement agreement for the court to approve.",
            'RI' => "File a complaint for divorce in the family court. Rhode Island requires six months of residency. Your spouse is served with the complaint. Rhode Island does not require a waiting period for contested or uncontested divorces. If both parties agree on all terms, you can file your settlement agreement for the judge to approve.",
            'SC' => "File a complaint in the family court. South Carolina requires six months of residency. Your spouse is served. South Carolina does not require a waiting period. If both parties agree on all issues and sign a marital settlement agreement, you can file it with the court for the judge to approve and sign.",
            'SD' => "File a complaint for divorce in the circuit court. South Dakota requires 60 days of residency. Your spouse is served. South Dakota requires a 60-day waiting period from service. After this period, if both parties agree on all terms, you can file your final judgment for the judge to enter.",
            'TN' => "File a complaint in the circuit court. Tennessee requires six months of residency. Your spouse is served. Tennessee does not require a waiting period. If both parties agree on all issues, you can file your final decree of divorce for the judge to approve and sign.",
            'TX' => "File a petition in the district court. Texas requires six months of residency. Your spouse is served with the petition. Texas requires a 60-day waiting period from filing. After this period, if both parties agree on all terms, you can file your final decree of divorce for the judge to sign.",
            'UT' => "File a petition for divorce in the district court. Utah requires six months of residency. Your spouse is served. Utah requires a 30-day waiting period from service. After this period, if both parties agree on all terms and issues, you can file your stipulated decree for the judge to enter.",
            'VT' => "File a complaint in the family court. Vermont requires six months of residency. Your spouse is served. Vermont does not require a waiting period. If both parties agree on all issues, you can file your settlement agreement for the judge to review and approve.",
            'VA' => "File a complaint in the circuit court. Virginia requires six months of residency. Your spouse is served. For uncontested divorces, Virginia requires either a six-month separation with a settlement agreement or one year separation without one. After meeting the requirement, file your agreement for the judge to approve.",
            'WA' => "File a petition for dissolution of marriage in the superior court. Washington requires 90 days of residency. Your spouse is served. Washington requires a 30-day waiting period from service. After this period, if both parties agree on all terms, you can file your final order for the judge to sign.",
            'WV' => "File a complaint in the circuit court. West Virginia requires six months of residency. Your spouse is served. West Virginia does not require a waiting period for uncontested divorces. If both parties agree on all terms, you can file your decree for the judge to approve and sign.",
            'WI' => "File a petition in the family court. Wisconsin requires six months of residency. Your spouse is served with the petition. Wisconsin requires a 120-day waiting period from filing before judgment can be entered. During this time, you negotiate terms. After the period, if both parties agree, the court enters the final judgment.",
            'WY' => "File a complaint for divorce in the district court. Wyoming requires six months of residency. Your spouse is served. Wyoming does not require a waiting period. If both parties agree on all issues, you can file your final decree of divorce for the judge to approve and sign.",
        ];

        foreach ($states as $code => $process) {
            DB::table('states')
                ->where('state_code', $code)
                ->update(['divorce_process' => $process]);
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        DB::table('states')->update(['divorce_process' => null]);
    }
}
