<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdateCustodyVerifiedBatch5SdThroughWy extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'SD')->update(['custody_of_child' => "South Dakota presumes joint physical custody if joint legal custody is awarded per SDCL 25-5-22.1. Courts consider best interests of child including parent relationships, ability to provide care, stability, continuity, adjustment to home/school, domestic violence, and child preferences if mature. House Bill 1104 (2019) created strong joint physical custody presumption. Source: South Dakota Codified Laws § 25-5-22.1."]);
        DB::table('states')->where('state_code', 'TN')->update(['custody_of_child' => "Tennessee requires clear and convincing evidence that joint custody is not in child's best interest per Tennessee Code Annotated § 36-6-101. Courts consider best interests factors including parent relationships, ability to provide care, stability, domestic violence, adjustment to home/school, and child preferences. Strong presumption favoring joint custody arrangements. Source: Tennessee Code Annotated § 36-6-101."]);
        DB::table('states')->where('state_code', 'TX')->update(['custody_of_child' => "Texas uses \"conservatorship\" terminology instead of custody. Presumes both parents should be designated Joint Managing Conservators (joint custody) per Texas Family Code § 153.001. Courts consider best interests including child's needs, parent relationships, stability, adjustment to home/school, domestic violence, and child's preferences. Both parents encouraged to stay involved. Source: Texas Family Code § 153.001."]);
        DB::table('states')->where('state_code', 'UT')->update(['custody_of_child' => "Utah courts determine custody based on best interests of child per Utah Code § 30-3-10. No presumption in favor of joint custody. Courts consider child's needs, parent relationships, ability to provide care, stability, continuity, domestic violence, adjustment to school, and child's preferences. Both parents' involvement encouraged when appropriate. Courts may award any custody arrangement in best interest. Source: Utah Code § 30-3-10."]);
        DB::table('states')->where('state_code', 'VT')->update(['custody_of_child' => "Vermont courts determine custody based on best interests of child per Vermont Statutes Title 15 § 665. No presumption in favor of joint custody. Courts consider child's needs, parent relationships, stability, continuity of care, adjustment to home/school, domestic violence, and child's preferences if mature. Both parents' involvement encouraged unless detrimental. Source: Vermont Statutes § 15-665."]);
        DB::table('states')->where('state_code', 'VA')->update(['custody_of_child' => "Virginia courts determine custody based on best interests of child per Virginia Code § 20-124. No presumption in favor of joint custody. Courts consider many factors including parent-child relationships, ability to provide care, stability, adjustment to home/school/community, continuity of care, domestic violence, substance abuse, and child preferences if mature. Both parents encouraged to maintain involvement. Source: Virginia Code § 20-124."]);
        DB::table('states')->where('state_code', 'WA')->update(['custody_of_child' => "Washington uses \"parenting plan\" terminology per Washington RCW 26.09.002. Courts presume equal residential placement is in child's best interest per RCW 26.09.002. Court must state reasons if not ordering substantial equal time-sharing. Factors include parent relationships, ability to provide care, stability, continuity, domestic violence, and child's wishes. Both parents' involvement presumed best. Source: Washington RCW 26.09.002."]);
        DB::table('states')->where('state_code', 'WV')->update(['custody_of_child' => "West Virginia courts determine custody based on best interests of child per West Virginia Code § 48-2-15. No statutory presumption in favor of joint custody. Courts consider parent-child relationships, ability to provide care, stability, continuity of care, adjustment to home/school, domestic violence, substance abuse, and child's preferences. Both parents' involvement encouraged unless detrimental. Source: West Virginia Code § 48-2-15."]);
        DB::table('states')->where('state_code', 'WI')->update(['custody_of_child' => "Wisconsin courts determine custody based on best interests of child per Wisconsin Statutes § 767.41. No presumption in favor of joint custody. Courts consider factors including wishes of parents and child, interaction and relationships, adjustment to home/school/community, ability to meet child's needs, domestic violence, and substance abuse. Both parents encouraged to maintain involvement with children. Source: Wisconsin Statutes § 767.41."]);
        DB::table('states')->where('state_code', 'WY')->update(['custody_of_child' => "Wyoming courts determine custody based on best interests of child per Wyoming Statutes § 20-2-201. No presumption in favor of joint custody. Courts consider best interests factors including parent relationships, ability to provide care, stability, adjustment to home/school, willingness to provide care, domestic violence, and child's preferences if mature. Both parents encouraged to maintain involvement with children. Source: Wyoming Statutes § 20-2-201."]);
    }

    public function down() { }
}
