<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdateDivorceProcessVerifiedBatch4NcThroughSc extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'NC')->update(['divorce_process' => "North Carolina divorce is filed in family court. One spouse must have resided in North Carolina for at least 6 months before filing (NC Gen Stat § 50-6). Parties must live separate and apart for 1 year before divorce is finalized (NC Gen Stat § 50-6). North Carolina allows no-fault divorce based on the 1-year separation. Both parties must reach agreement or court determines custody, support, and property division. Source: NC General Statutes Chapter 50."]);
        DB::table('states')->where('state_code', 'ND')->update(['divorce_process' => "North Dakota divorce is filed in district court. One spouse must reside in North Dakota for 6 months before filing per North Dakota Century Code § 14-05-17. There is no mandatory waiting period after filing. North Dakota is a no-fault divorce state allowing dissolution for irreconcilable differences. Both parties must reach agreement or court determines custody, support, and property division. Source: North Dakota Century Code Title 14."]);
        DB::table('states')->where('state_code', 'NM')->update(['divorce_process' => "New Mexico divorce is filed in district court. One spouse must be domiciled in New Mexico for 6 months before filing per New Mexico Statutes § 40-4-5. There is a mandatory 30-day waiting period from filing before final decree per New Mexico Statutes § 40-4-7. New Mexico allows no-fault dissolution of marriage based on irretrievable breakdown. Both parties must reach agreement or court determines issues. Source: New Mexico Statutes Chapter 40."]);
        DB::table('states')->where('state_code', 'NY')->update(['divorce_process' => "New York divorce is filed in Supreme Court. One spouse must reside in New York for 1 year before filing per NY Domestic Relations Law § 170. New York has no mandatory waiting period. New York allows divorce based on cruel and inhuman treatment, abandonment, adultery, separation judgment, or irretrievable breakdown of the marriage. Both parties must reach agreement or court determines custody, support, and property division. Source: New York Domestic Relations Law Article 10."]);
        DB::table('states')->where('state_code', 'OH')->update(['divorce_process' => "Ohio divorce is filed in court. One spouse must reside in Ohio for 6 months and in the county for 90 days before filing per Ohio Revised Code § 3105.03. For dissolution of marriage, there is a mandatory 30-day waiting period from filing per ORC § 3105.62. Ohio allows no-fault divorce based on irretrievable breakdown. Both parties must reach agreement or court determines custody, support, and property division. Source: Ohio Revised Code Chapter 3105."]);
        DB::table('states')->where('state_code', 'OK')->update(['divorce_process' => "Oklahoma divorce is filed in court. One spouse must reside in Oklahoma for 6 months in good faith before filing per Oklahoma Statutes § 43-102. There is a mandatory 90-day waiting period with minor children per Oklahoma Statutes § 43-107.1. Oklahoma allows no-fault divorce. Both parties must reach agreement or court determines custody, support, and property division. The 90-day period can be waived for good cause if opposing party agrees. Source: Oklahoma Statutes Title 43."]);
        DB::table('states')->where('state_code', 'OR')->update(['divorce_process' => "Oregon divorce is filed in circuit court. One spouse must be resident or domiciled in Oregon for 6 months before filing per Oregon Revised Statutes § 107.075. There is a mandatory 90-day waiting period from filing before dissolution can be finalized (ORS § 107.135). Oregon allows no-fault dissolution based on irreconcilable differences. Both parties must reach agreement or court determines custody, support, and property division. Source: Oregon Revised Statutes Chapter 107."]);
        DB::table('states')->where('state_code', 'PA')->update(['divorce_process' => "Pennsylvania divorce is filed in court. One spouse must reside in Pennsylvania for 6 months before filing per Title 23 § 3701. Pennsylvania has no mandatory waiting period. Pennsylvania allows both fault-based divorce (adultery, cruel and inhuman treatment, abandonment) and no-fault divorce. Both parties must reach agreement or court determines custody, support, and property division. Source: Pennsylvania Consolidated Statutes Title 23."]);
        DB::table('states')->where('state_code', 'RI')->update(['divorce_process' => "Rhode Island divorce is filed in family court. One spouse must have been a domiciled inhabitant of Rhode Island for 1 year before filing per Rhode Island General Laws § 15-5-12. There is a mandatory 3-month waiting period from the judgment until final decree per RI Gen Laws § 15-5-23. Rhode Island allows both fault and no-fault grounds including irreconcilable differences. Court determines custody, support, and property division. Source: Rhode Island General Laws Chapter 15-5."]);
        DB::table('states')->where('state_code', 'SC')->update(['divorce_process' => "South Carolina divorce is filed in court. One spouse must reside in South Carolina for 1 year (3 months if both in-state) before filing per South Carolina Code § 20-3-10. For no-fault divorce, parties must live separate and apart for 1 year per SC Code § 20-3-10. For fault-based divorce, no separation period required. There is a mandatory 90-day waiting period after filing per SC Code § 20-3-150. Source: South Carolina Code Title 20."]);
    }

    public function down() { }
}
