<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdateMediationSupportVerifiedBatch3MaThroughNj extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'MA')->update(['mediation_support' => "Massachusetts encourages mediation in family law matters through Massachusetts General Laws c.251. Mediation available by agreement or court referral. Court may order mediation for any civil dispute including family matters. Not mandatory statewide. Certified mediators available through state program. Parties share costs or each hire private mediators. Mediation communications confidential and privileged. Court may enforce mediation agreements. Source: Massachusetts General Laws c.251."]);
        DB::table('states')->where('state_code', 'MI')->update(['mediation_support' => "Michigan encourages mediation in family law cases through Michigan Court Rules 2.410 et seq. Mediation available by agreement or court order. Not mandatory statewide but court may order mediation. Certified mediators available through court system. Costs typically shared by parties or determined by mediator agreement. Mediation communications confidential under state law. Court-connected programs available in many courts. Source: Michigan Court Rules 2.410."]);
        DB::table('states')->where('state_code', 'MN')->update(['mediation_support' => "Minnesota strongly encourages mediation in family law disputes under Minnesota Statutes § 518.619. Mediation available by agreement or court order for custody/visitation matters. Court may order mediation for contested issues. Not mandatory but highly recommended. Certified family mediators available. Parties typically split mediator costs equally. Mediation communications confidential. Court-connected programs available. Source: Minnesota Statutes § 518.619."]);
        DB::table('states')->where('state_code', 'MS')->update(['mediation_support' => "Mississippi encourages mediation in family law matters through Mississippi Rules of Civil Procedure 26. Mediation available by agreement or court order. Court may refer cases to mediation. Not mandatory statewide. Certified mediators available through court system. Parties may share costs or each hire mediators. Mediation communications confidential and privileged. Court retains authority over unresolved issues. Source: Mississippi Rules of Civil Procedure 26."]);
        DB::table('states')->where('state_code', 'MO')->update(['mediation_support' => "Missouri encourages mediation in family law cases under Missouri Supreme Court Rules § 17.01 et seq. Mediation available by agreement or court order. Court may order mediation at any stage of litigation. Not mandatory but strongly encouraged. Certified mediators available. Costs shared by parties unless court orders otherwise. Mediation communications confidential and privileged. Source: Missouri Supreme Court Rules § 17.01."]);
        DB::table('states')->where('state_code', 'MT')->update(['mediation_support' => "Montana encourages mediation in family law disputes through Montana Rules of Civil Procedure. Mediation available by agreement or court order. Court may refer cases to mediation. Not mandatory statewide. Certified mediators available through court programs. Parties may share costs equally. Mediation communications confidential under state law. Court retains authority over unresolved issues. Source: Montana Rules of Civil Procedure."]);
        DB::table('states')->where('state_code', 'NE')->update(['mediation_support' => "Nebraska encourages mediation in family law matters through Nebraska Supreme Court Rules of Practice §§ 1-300 et seq. Mediation available by agreement or court order. Court may order mediation for child custody/visitation disputes. Not mandatory statewide. Certified mediators available. Parties typically share costs equally. Mediation communications confidential. Good faith participation expected. Source: Nebraska Supreme Court Rules of Practice."]);
        DB::table('states')->where('state_code', 'NV')->update(['mediation_support' => "Nevada requires mediation for certain family law disputes under Nevada Revised Statutes § 33.010 et seq. Mediation available by agreement or court order for custody and visitation disputes. Court may order mediation before trial. Certified mediators available through court system. Parties typically share mediator costs. Mediation communications confidential. Court may enforce mediation agreements. Source: Nevada Revised Statutes § 33.010."]);
        DB::table('states')->where('state_code', 'NH')->update(['mediation_support' => "New Hampshire encourages mediation in family law cases through New Hampshire Statutes Annotated § 328-C. Mediation available by agreement or court order. Court may refer cases to mediation. Not mandatory statewide. Certified mediators available through state program. Parties may share costs or each hire mediators. Mediation communications confidential and privileged. Source: New Hampshire Statutes Annotated § 328-C."]);
        DB::table('states')->where('state_code', 'NJ')->update(['mediation_support' => "New Jersey requires mediation before family law trials under New Jersey Court Rules § 5:1-1 et seq. Mediation is mandatory for contested custody and visitation disputes before trial. Court-ordered mediation available at reduced fees. Parties may hire private mediators. Costs shared equally unless court orders otherwise. Mediation communications confidential. Exceptions available for domestic violence. Source: New Jersey Court Rules § 5:1-1."]);
    }

    public function down() { }
}
