<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdateDivorceProcessVerifiedBatch5SdThroughWy extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'SD')->update(['divorce_process' => "South Dakota divorce has minimal residency requirements. One spouse must be a resident of South Dakota when filing per SDCL 25-4-30. There is a mandatory 60-day waiting period from filing before divorce is finalized. South Dakota allows no-fault divorce. Both parties must reach agreement or court determines custody, support, and property division. Filing can happen immediately upon residency establishment. Source: South Dakota Codified Laws Title 25."]);
        DB::table('states')->where('state_code', 'TN')->update(['divorce_process' => "Tennessee divorce is filed in court. One spouse must have resided in Tennessee for 6 months before filing per TCA 36-4-104. For divorces with minor children, there is a 90-day waiting period from filing; without minor children, a 60-day waiting period applies (TCA 36-4-106). Tennessee allows both fault and no-fault divorce grounds. Both parties must reach agreement or court determines issues. Source: Tennessee Code Annotated Title 36."]);
        DB::table('states')->where('state_code', 'TX')->update(['divorce_process' => "Texas divorce is filed in district court. One spouse must have been domiciled in Texas for 6 months and in the county for 90 days before filing per Texas Family Code § 6.001. There is a mandatory 60-day waiting period from service of petition before final divorce decree can be entered per Family Code § 6.702. Texas allows both fault and no-fault divorce. Property is divided equitably or per community property principles. Source: Texas Family Code Title 1."]);
        DB::table('states')->where('state_code', 'UT')->update(['divorce_process' => "Utah divorce is filed in court. One spouse must be an actual and bona fide resident of the county for 90 days before filing per Utah Code § 30-3-1. There is no mandatory state-wide waiting period, but courts may impose wait periods. Utah allows no-fault divorce based on irreconcilable differences. Both parties must reach agreement or court determines custody, support, and property division. Source: Utah Code Title 30."]);
        DB::table('states')->where('state_code', 'VT')->update(['divorce_process' => "Vermont divorce is filed in court. One spouse must have resided in Vermont for 6 months before filing per Vermont Statutes Title 15 § 605. There is a mandatory 6-month waiting period from filing before divorce can be finalized per Vermont law. Vermont allows no-fault divorce based on irreconcilable differences. Both parties must reach agreement or court determines custody, support, and property division. Source: Vermont Statutes Title 15."]);
        DB::table('states')->where('state_code', 'VA')->update(['divorce_process' => "Virginia divorce is filed in circuit court. One spouse must have been a bona fide resident of Virginia for 6 months before filing per Virginia Code § 20-91. Virginia has no mandatory waiting period after filing. Virginia allows both fault and no-fault divorce based on 6-month separation or grounds like adultery or cruelty. Both parties must reach agreement or court determines custody, support, and property division. Source: Virginia Code Title 20."]);
        DB::table('states')->where('state_code', 'WA')->update(['divorce_process' => "Washington divorce (dissolution of marriage) is filed in court. One spouse must reside in Washington for 90 days before filing per Washington RCW 26.09.030. There is a mandatory 90-day waiting period from filing before final judgment can be entered per Washington law. Washington allows no-fault dissolution based on irreconcilable differences. Both parties must reach agreement or court determines custody, support, and property division. Source: Washington Revised Code of Washington Chapter 26.09."]);
        DB::table('states')->where('state_code', 'WV')->update(['divorce_process' => "West Virginia divorce is filed in court. One spouse must have resided in West Virginia for 12 months before filing per West Virginia Code § 48-5-101. For no-fault divorce, parties must have lived separate and apart for 1 year. There is a 20-day waiting period from filing (WV Code § 48-5-203). West Virginia allows no-fault and fault-based divorce grounds. Court determines custody, support, and property division. Source: West Virginia Code Chapter 48, Article 5."]);
        DB::table('states')->where('state_code', 'WI')->update(['divorce_process' => "Wisconsin divorce is filed in court. One spouse must have resided in Wisconsin for 6 months and in the county for 30 days before filing per Wisconsin Statutes § 767.087. There is a mandatory 120-day waiting period from filing before divorce decree can be entered per Wisconsin law. Wisconsin allows no-fault divorce based on irretrievable breakdown. Both parties must reach agreement or court determines custody, support, and property division. Source: Wisconsin Statutes Chapter 767."]);
        DB::table('states')->where('state_code', 'WY')->update(['divorce_process' => "Wyoming divorce is filed in district court. One spouse must have been a resident of Wyoming for at least 60 days before filing per Wyoming Statutes § 20-1-101. Wyoming has no mandatory waiting period after filing. Wyoming allows no-fault divorce based on irreconcilable differences. Both parties must reach agreement or court determines custody, support, and property division. Wyoming is known as a divorce-friendly state with minimal waiting periods and residency. Source: Wyoming Statutes Title 20."]);
    }

    public function down() { }
}
