<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdateCustodyVerifiedBatch4NcThroughSc extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'NC')->update(['custody_of_child' => "North Carolina has no presumption for joint custody even if requested per NC Gen Stat § 50-13.2. Courts consider best interests without presumption favoring either parent. Custody may be granted exclusively, jointly, or to multiple persons/agencies. Orders include visitation terms promoting child's interest and welfare. Considerations include parent relationships, stability, and domestic violence. Source: NC General Statutes § 50-13.2."]);
        DB::table('states')->where('state_code', 'ND')->update(['custody_of_child' => "North Dakota does not have presumption in favor of joint custody per ND Cent Code § 14-09-06.2. However, legislature established presumption for joint legal custody granting each parent certain rights and duties. Courts consider best interests and welfare of child including parent relationships, ability to provide care, stability, domestic violence, and child preferences. Source: North Dakota Century Code § 14-09-06.2."]);
        DB::table('states')->where('state_code', 'NM')->update(['custody_of_child' => "New Mexico presumes joint custody is in child's best interest per New Mexico Statutes § 40-4-9.1. Joint custody presumption applies in initial custody determinations. Award of joint custody does not imply equal financial responsibility. Courts consider best interests, parent relationships, ability to provide care, stability, domestic violence, and child preferences. Parenting plan required. Source: New Mexico Statutes § 40-4-9.1."]);
        DB::table('states')->where('state_code', 'NY')->update(['custody_of_child' => "New York awards custody based on best interests of child per Domestic Relations Law § 236. No statutory presumption for joint custody. Courts consider custody preferences of parents, parent-child relationships, ability to provide care, stability, continuity, adjustment to home/school, and domestic violence. Both parents' involvement encouraged unless contrary to best interests. Source: New York Domestic Relations Law § 236."]);
        DB::table('states')->where('state_code', 'OH')->update(['custody_of_child' => "Ohio courts determine custody based on best interests of child per Ohio Revised Code § 3119.01. No presumption in favor of joint custody. Courts consider parent-child relationships, ability to provide care, stability, continuity of care, domestic violence, substance abuse, and child's preferences if mature. Both parents' involvement encouraged unless detrimental. Source: Ohio Revised Code Chapter 3119."]);
        DB::table('states')->where('state_code', 'OK')->update(['custody_of_child' => "Oklahoma courts determine custody based on best interests of child. No statutory presumption in favor of joint custody. Court evaluates which parent better promotes child's welfare. Considerations include parent-child relationships, ability to meet needs, stability, domestic violence, substance abuse, and child's preferences if appropriate. Courts have discretion in custody arrangements. Source: Oklahoma Statutes Title 43."]);
        DB::table('states')->where('state_code', 'OR')->update(['custody_of_child' => "Oregon courts do not presume joint custody per Oregon Revised Statutes § 107.137. Courts evaluate specific custody dispute facts to determine best interests. Rebuttable presumption against custody for parent who committed abuse. Considerations include parent-child relationships, ability to provide care, stability, cooperation capacity, and child adjustment. Both parents' involvement encouraged unless detrimental. Source: Oregon Revised Statutes § 107.137."]);
        DB::table('states')->where('state_code', 'PA')->update(['custody_of_child' => "Pennsylvania awards custody based on best interests of child per Title 23. Courts evaluate parent ability to meet child needs. No presumption in favor of joint custody. Considerations include parent-child relationships, ability to provide stability, continuity of care, adjustment to home/school, health and welfare needs, and child's preferences if mature. Both parents' involvement encouraged. Source: Pennsylvania Title 23 § 5328."]);
        DB::table('states')->where('state_code', 'RI')->update(['custody_of_child' => "Rhode Island awards custody based on best interests of child per Rhode Island General Laws § 15-5-16. No presumption in favor of joint custody. Courts consider child's adjustment to home and school, stability, health and welfare, parent relationships, ability to provide care, and child's preferences. Guideline considerations in § 15-5-16(c) used to determine custody arrangements. Source: Rhode Island General Laws § 15-5-16."]);
        DB::table('states')->where('state_code', 'SC')->update(['custody_of_child' => "South Carolina awards custody based on best interests of child per South Carolina Code § 20-3-160. No presumption favoring joint custody. Courts consider primary caretaker role, ability to provide care, stability, adjustment to home/school, parent relationships, domestic violence, and child's preferences if mature. Both parents' involvement encouraged when appropriate. Custody determined case-by-case. Source: South Carolina Code § 20-3-160."]);
    }

    public function down() { }
}
