<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdateSpousalSupportVerifiedBatch5SdThroughWy extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'SD')->update(['spousal_support_rules' => "South Dakota awards spousal support under South Dakota Codified Law § 25-4-44. Court may award based on need and ability to pay. Factors: earning capacity, education/training, age/health, standard of living during marriage, length of marriage, ability to be self-supporting. No formula; judges have discretion. Support may be indefinite or term-limited. Terminates upon remarriage, cohabitation, or substantial change in circumstances. Source: South Dakota Codified Laws § 25-4-44."]);
        DB::table('states')->where('state_code', 'TN')->update(['spousal_support_rules' => "Tennessee awards alimony under Tennessee Code § 36-5-121. Court may award rehabilitative, transitional, or permanent alimony. No formula; judges have broad discretion. Factors: earning capacity, education/training, standard of living, age/health, marriage length, contributions, financial resources, and ability to become self-supporting. Alimony terminates upon death, remarriage, or cohabitation with another adult. Modifiable for substantial change in circumstances. Source: Tennessee Code § 36-5-121."]);
        DB::table('states')->where('state_code', 'TX')->update(['spousal_support_rules' => "Texas awards spousal maintenance under Texas Family Code § 8.051. Eligibility limited: obligee must lack property for needs or be unable to support through employment after 10-year marriage or marriage with domestic violence/abuse. Guideline amount: 20% of payer income capped at $5,250/month, or other amount if justified. Duration: no more than 5 years unless marriage 20+ years. Terminates upon death, remarriage, or cohabitation. Source: Texas Family Code § 8.051-8.060."]);
        DB::table('states')->where('state_code', 'UT')->update(['spousal_support_rules' => "Utah awards spousal support under Utah Code § 30-3-5. Court may award based on need and ability to pay. No formula; factors: earning capacity, financial resources, length of marriage, standard of living during marriage, contributions, age/health, custody of children, and property disposition. Support may be for specified period or indefinite. Terminates upon death, remarriage, cohabitation, or substantial change in circumstances. Modifiable upon substantial change. Source: Utah Code § 30-3-5."]);
        DB::table('states')->where('state_code', 'VT')->update(['spousal_support_rules' => "Vermont awards spousal support (maintenance) under Vermont Statutes Title 15 § 752. Court may award indefinite or term alimony. No formula; factors: standard of living, financial resources, earning capacity, age/health, education, ability to be self-supporting, contributions, length of marriage, and other relevant factors. Modifiable for substantial change in circumstances. Alimony terminates upon death, remarriage, or sustained cohabitation. Source: Vermont Statutes Title 15 § 752."]);
        DB::table('states')->where('state_code', 'VA')->update(['spousal_support_rules' => "Virginia awards spousal support under Virginia Code § 20-107.1 et seq. Durational support: limited duration. No formula; judges have discretion. Factors: financial resources/needs, earnings, earning capacity, standard of living during marriage, contributions to education/earnings, length of marriage, age/health, custody of children. Alimony terminates upon remarriage or cohabitation. Exception: may continue through remarriage if by prior agreement. Modifiable for substantial change. Source: Virginia Code § 20-107.1."]);
        DB::table('states')->where('state_code', 'WA')->update(['spousal_support_rules' => "Washington awards spousal maintenance under Washington Revised Code § 26.09.090. Court may award temporary or permanent maintenance. No formula; factors: financial resources, earning capacity, ability to become self-supporting, property received in settlement, length of marriage, age/health, education, custody of children, and other relevant factors. Court has broad discretion. Modifiable upon substantial change in circumstances. Source: Washington Revised Code § 26.09.090."]);
        DB::table('states')->where('state_code', 'WV')->update(['spousal_support_rules' => "West Virginia awards alimony under West Virginia Code § 48-2-32. Court may award alimony to spouse lacking sufficient property and unable to be self-supporting or unable to work due to custody of young child. Duration not to exceed length of marriage unless for good cause. Court determines amount based on financial condition of both parties and other relevant factors. Alimony terminates upon remarriage or death of either party. Modifiable for material change in circumstances. Source: West Virginia Code § 48-2-32."]);
        DB::table('states')->where('state_code', 'WI')->update(['spousal_support_rules' => "Wisconsin awards spousal support (maintenance) under Wisconsin Statutes § 767.26. Court determines support amount using guideline factors; no formula. Guideline recommendations: 17% of difference between spouses' incomes for indefinite support, or 20% for limited term. Factors: length of marriage, age/health, earning capacity, education, property division, contributions. Support may be temporary, indefinite, or term-limited. Terminates upon death, remarriage, or substantial change. Source: Wisconsin Statutes § 767.26."]);
        DB::table('states')->where('state_code', 'WY')->update(['spousal_support_rules' => "Wyoming awards spousal support under Wyoming Statutes § 20-2-114. Court may award based on need and ability to pay. No formula; judges have discretion. Factors: earning capacity, financial situation, education/training, length of marriage, standard of living, contributions, age/health, and property disposition. Support may be indefinite or term-limited. Terminates upon death, remarriage, or cohabitation. Modifiable for substantial change in circumstances. Source: Wyoming Statutes § 20-2-114."]);
    }

    public function down() { }
}
