<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdatePropertyDivisionVerifiedBatch3MaThroughNj extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'MA')->update(['property_division' => "Massachusetts is equitable distribution state per MGL c.208 § 34. Court divides marital property fairly but not necessarily equally. Separate property (before marriage, inherited, gifted) not divided. Courts consider length of marriage, financial condition of each spouse, contributions to property acquisition, earning capacity, and other factors. All property owned by either spouse subject to division. Source: MGL c.208 § 34."]);
        DB::table('states')->where('state_code', 'MI')->update(['property_division' => "Michigan is equitable distribution state per MCL 552.401. Court divides marital property fairly. Separate property includes assets owned before marriage and inheritances. Michigan considers length of marriage, financial condition of each spouse, contribution to property acquisition, earning capacity, and other factors. Property acquired during marriage presumed marital property. Source: MCL 552.401."]);
        DB::table('states')->where('state_code', 'MN')->update(['property_division' => "Minnesota is equitable distribution state per Minnesota Statutes § 518.58. Court divides marital property in manner deemed \"just and equitable\" (not necessarily equal). Separate property (before marriage, inherited) not divided. Courts consider length of marriage, contributions to property, earning capacity, financial condition, and future opportunity for capital acquisition. Courts value assets as of settlement conference date. Source: Minnesota Statutes § 518.58."]);
        DB::table('states')->where('state_code', 'MS')->update(['property_division' => "Mississippi is equitable distribution state per Mississippi Code § 93-5-23. Court divides marital property fairly. Assets acquired during marriage subject to equitable division unless proven to be separate property (before marriage, inherited, gifted). Court considers economic circumstances, nature of case, and what is equitable and just. Alimony and support considered separately. Source: Mississippi Code § 93-5-23."]);
        DB::table('states')->where('state_code', 'MO')->update(['property_division' => "Missouri is equitable distribution state per Missouri Revised Statutes § 452.330. Court divides marital property in manner deemed \"just\" (not necessarily equal). Separate property set apart to each spouse. Courts consider economic circumstances, contributions of each spouse (including homemaker contributions), and value of separate property. Broad discretion for fair allocation. Source: Missouri Revised Statutes § 452.330."]);
        DB::table('states')->where('state_code', 'MT')->update(['property_division' => "Montana is equitable distribution state per Montana Code Annotated § 40-4-202. Court equitably apportions property belonging to either or both spouses \"without regard to marital misconduct.\" Equitable division is fair but not necessarily equal. Courts consider length of marriage, ages, occupation, income, contributions to property, and child custody. For children's welfare, may set aside portion of marital property. Source: Montana Code Annotated § 40-4-202."]);
        DB::table('states')->where('state_code', 'NE')->update(['property_division' => "Nebraska is equitable distribution state per Nebraska Revised Statutes § 42-365. Court divides marital property fairly in manner deemed \"just and equitable.\" Process: classify as marital or nonmarital, value marital assets/liabilities, distribute equitably. General rule: award 1/3 to 1/2 of marital estate with fairness and reasonableness as standard. Courts consider duration of marriage, contributions, interruption of careers. Source: Nebraska Revised Statutes § 42-365."]);
        DB::table('states')->where('state_code', 'NV')->update(['property_division' => "Nevada is community property state per Nevada Revised Statutes § 125.150. Court makes equal disposition of community property except for compelling reasons (which must be written). Separate property (before marriage, inherited, designated) remains with owning spouse. Community property acquired during marriage divided 50/50 unless unequal division justified. Source: Nevada Revised Statutes § 125.150."]);
        DB::table('states')->where('state_code', 'NH')->update(['property_division' => "New Hampshire is equitable distribution state per New Hampshire RSA 458:16-a. Court presumes equal division is equitable unless otherwise warranted. Property includes tangible and intangible assets, benefits, and retirement accounts. Court considers length of marriage, age/health, earning capacity, contributions to property acquisition, domestic violence, and other factors. Court shall specify written reasons for unequal division. Source: New Hampshire RSA 458:16-a."]);
        DB::table('states')->where('state_code', 'NJ')->update(['property_division' => "New Jersey is equitable distribution state per New Jersey Revised Statutes § 2A:34-23.1. Court divides marital property fairly based on multiple factors. Considers duration of marriage, age/health, income/property brought to marriage, standard of living, written agreements, economic circumstances, income/earning capacity, and contributions of each party (financial and nonfinancial, including homemaking). Court must make specific findings on all relevant issues. Source: New Jersey Revised Statutes § 2A:34-23.1."]);
    }

    public function down() { }
}
