<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdateMediationSupportVerifiedBatch1AlThroughGa extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'AL')->update(['mediation_support' => "Alabama encourages mediation in divorce cases under Alabama Rule of Civil Procedure 26.4. Mediation is not mandatory but is strongly recommended for contested issues. Parties may agree to mediate custody, support, or property division. Mediators are typically paid by agreement of parties or may be court-appointed. Court rules allow judges to order mediation in appropriate cases. Mediation is confidential and communications are privileged. Source: Alabama Rule of Civil Procedure 26.4."]);
        DB::table('states')->where('state_code', 'AK')->update(['mediation_support' => "Alaska requires mediation for custody and visitation disputes under Alaska Statutes § 09.62.100. Court may order mediation for contested child-related issues. Mediation is available for all family law disputes by agreement. Costs typically shared equally by parties unless court orders otherwise. Mediator qualifications vary; court-appointed mediators must meet state standards. Mediation is confidential under Alaska law. Source: Alaska Statutes § 09.62.100 et seq."]);
        DB::table('states')->where('state_code', 'AZ')->update(['mediation_support' => "Arizona requires Alternative Dispute Resolution (ADR) including mediation for most family law cases under Arizona Rules of Family Law Procedure 81. Court may order mediation for custody, visitation, support, and property division. Parties pay mediator costs unless waived for financial hardship. Certified family mediators available through court system. Mediation meetings are confidential. Non-compliance with mediation order may result in sanctions. Source: Arizona Rules of Family Law Procedure 81."]);
        DB::table('states')->where('state_code', 'AR')->update(['mediation_support' => "Arkansas encourages mediation in family law matters under Arkansas Code § 34-52-201. Mediation available by consent or court order. Not mandatory for all cases. Costs split between parties unless agreed otherwise. Court may order mediation for custody disputes and other contested issues. Mediators must be certified or approved by court. Mediation is confidential and privileged communication. Source: Arkansas Code § 34-52-201 et seq."]);
        DB::table('states')->where('state_code', 'CA')->update(['mediation_support' => "California requires mediation for custody and visitation disputes under California Family Code § 3160. Mediation is mandatory before trial on contested child custody/visitation issues. Court-connected mediation available at reduced fees. Parties may hire private mediators. Costs typically paid by parties or may be charged to county. Mediation is confidential under Family Code § 3177. Exceptions available for domestic violence or mutual consent to waive. Source: California Family Code § 3160-3188."]);
        DB::table('states')->where('state_code', 'CO')->update(['mediation_support' => "Colorado strongly encourages mediation in all family law cases under Colorado Rule of Civil Procedure 121 § 1-4-4. Court may order mediation for disputed issues. Mediation not mandatory but highly recommended. Parties may share mediator costs or each hire private mediators. Court-appointed mediators available. Mediation communications are confidential. Court rules allow flexibility in mediation processes. Source: Colorado Rules of Civil Procedure 121 § 1-4-4."]);
        DB::table('states')->where('state_code', 'CT')->update(['mediation_support' => "Connecticut requires mediation for child custody disputes under Connecticut General Statutes § 46b-53a. Court-ordered mediation is mandatory before contested custody trial. Free or low-cost court-connected mediation available. Private mediators may be used by agreement. Mediators trained in family dynamics and child welfare. Mediation is confidential under state law. Parties must participate in good faith or face sanctions. Source: Connecticut General Statutes § 46b-53a."]);
        DB::table('states')->where('state_code', 'DE')->update(['mediation_support' => "Delaware encourages mediation in family law cases through Delaware Family Court Rules. Mediation available by agreement or court order. Not mandatory but recommended for all contested issues. Court-connected mediation program available. Parties may hire private mediators. Costs shared by agreement or mediator fees split equally. Mediation communications confidential under Delaware law. Court has discretion to order mediation. Source: Delaware Family Court Rules."]);
        DB::table('states')->where('state_code', 'FL')->update(['mediation_support' => "Florida requires mediation in all family law cases except domestic violence situations under Florida Statutes § 44.102. Mediation is mandatory before final hearing on contested issues. Court-connected mediation available. Parties pay mediator from certified provider list. Costs range from low-cost court program to private mediator fees. Mediation is confidential under Florida law. Exceptions available for good cause shown. Source: Florida Statutes § 44.102."]);
        DB::table('states')->where('state_code', 'GA')->update(['mediation_support' => "Georgia encourages mediation in family law matters through O.C.G.A. § 34-7-2. Mediation available by agreement or court referral. Not mandatory statewide but may be required by local court rule. Parties may use certified mediators or agree on private mediators. Costs determined by mediator agreement. Mediation is confidential and inadmissible in evidence. Court may refer unresolved issues to mediation. Source: O.C.G.A. § 34-7-2."]);
    }

    public function down() { }
}
