<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdateMediationSupportVerifiedBatch4NcThroughSc extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'NC')->update(['mediation_support' => "North Carolina encourages mediation in family law cases through North Carolina General Statutes § 50-13.1. Mediation available by agreement or court order. Court may order mediation for custody, visitation, and support disputes. Not mandatory statewide. Certified mediators available through court system. Parties typically share costs equally. Mediation communications confidential under state law. Court retains final decision-making authority. Source: North Carolina General Statutes § 50-13.1."]);
        DB::table('states')->where('state_code', 'ND')->update(['mediation_support' => "North Dakota encourages mediation in family law disputes through North Dakota Century Code § 14-01-09. Mediation available by agreement or court referral. Court may order mediation for child-related issues. Not mandatory statewide. Certified mediators available. Parties may share costs equally. Mediation communications confidential and privileged. Court may enforce mediation agreements. Source: North Dakota Century Code § 14-01-09."]);
        DB::table('states')->where('state_code', 'NM')->update(['mediation_support' => "New Mexico requires mediation for certain family law disputes under New Mexico Statutes § 40-4-7. Mediation available by agreement or court order for contested child custody issues. Court-ordered mediation available. Certified mediators available through court system. Costs typically shared by parties. Mediation communications confidential. Court may sanction non-compliance. Good faith participation required. Source: New Mexico Statutes § 40-4-7."]);
        DB::table('states')->where('state_code', 'NY')->update(['mediation_support' => "New York encourages mediation in family law cases through New York Domestic Relations Law § 236 and CPLR. Mediation available by agreement or court order. Court may refer cases to mediation. Not mandatory but strongly promoted. Certified mediators available through court programs and private practice. Costs shared by agreement. Mediation communications confidential. Court-connected programs available in many counties. Source: New York Domestic Relations Law § 236."]);
        DB::table('states')->where('state_code', 'OH')->update(['mediation_support' => "Ohio encourages mediation in family law disputes through Ohio Revised Code § 3109.052. Mediation available by agreement or court order for child custody matters. Court may order mediation before trial. Not mandatory statewide. Certified mediators available through court system. Parties typically share costs equally. Mediation communications confidential. Court retains authority over unresolved issues. Source: Ohio Revised Code § 3109.052."]);
        DB::table('states')->where('state_code', 'OK')->update(['mediation_support' => "Oklahoma encourages mediation in family law matters through Oklahoma Statutes Title 75 § 301 et seq. Mediation available by agreement or court order. Court may order mediation for any civil dispute including family law. Not mandatory statewide. Certified mediators available. Parties may share costs equally. Mediation communications confidential and privileged. Court may enforce mediation settlements. Source: Oklahoma Statutes Title 75 § 301."]);
        DB::table('states')->where('state_code', 'OR')->update(['mediation_support' => "Oregon requires mediation in certain family law cases under Oregon Revised Statutes § 109.701 et seq. Mediation required for contested custody disputes unless waived. Court-ordered mediation available. Certified family mediators available. Parties typically share costs equally unless court orders otherwise. Mediation communications confidential. Parties must participate in good faith. Source: Oregon Revised Statutes § 109.701."]);
        DB::table('states')->where('state_code', 'PA')->update(['mediation_support' => "Pennsylvania encourages mediation in family law disputes through Pennsylvania Rules of Civil Procedure. Mediation available by agreement or court order. Court may refer cases to mediation. Not mandatory statewide but available in many counties. Certified mediators available through court programs. Costs determined by mediator agreement. Mediation communications confidential and privileged. Source: Pennsylvania Rules of Civil Procedure."]);
        DB::table('states')->where('state_code', 'RI')->update(['mediation_support' => "Rhode Island encourages mediation in family law cases through Rhode Island General Laws § 40-6-1 et seq. Mediation available by agreement or court order. Court may order mediation for custody and visitation disputes. Not mandatory statewide. Certified mediators available through state program. Parties share costs or each hire mediators. Mediation communications confidential. Source: Rhode Island General Laws § 40-6-1."]);
        DB::table('states')->where('state_code', 'SC')->update(['mediation_support' => "South Carolina encourages mediation in family law matters through South Carolina Code § 15-2-40 et seq. Mediation available by agreement or court order. Court may order mediation before trial for custody or support disputes. Not mandatory statewide. Certified mediators available through court system. Parties typically share costs equally. Mediation communications confidential. Court retains authority over unresolved issues. Source: South Carolina Code § 15-2-40."]);
    }

    public function down() { }
}
