<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdatePropertyDivisionVerifiedBatch5SdThroughWy extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'SD')->update(['property_division' => "South Dakota is equitable distribution state per South Dakota Codified Laws § 25-4-44. Court divides marital property fairly but not necessarily equally. Separate property includes property owned before marriage, inherited, and gifted. Courts consider length of marriage, financial condition, contributions to property acquisition, earning capacity, and other factors. All property acquired during marriage subject to equitable division. Source: South Dakota Codified Laws § 25-4-44."]);
        DB::table('states')->where('state_code', 'TN')->update(['property_division' => "Tennessee is equitable distribution state per Tennessee Code Annotated § 36-4-121. Court divides marital property equitably and justly. Separate property (owned before marriage, inherited, gifted, by agreement) not divided. Courts consider length of marriage, financial condition, contribution to property acquisition, earning capacity, and other factors. Property acquired during marriage presumed marital property. Source: Tennessee Code Annotated § 36-4-121."]);
        DB::table('states')->where('state_code', 'TX')->update(['property_division' => "Texas is community property state per Texas Family Code § 3.002. Property acquired during marriage is community property and divided 50/50 unless agreement otherwise (may be 60/40 if circumstances warrant). Separate property (before marriage, inherited, gifted) remains with owning spouse. Community property is presumed property acquired during marriage. Strict 50/50 division presumption. Source: Texas Family Code § 3.002."]);
        DB::table('states')->where('state_code', 'UT')->update(['property_division' => "Utah is equitable distribution state per Utah Code § 30-3-5. Court divides marital property equitably. Separate property (owned before marriage, inherited, designated by agreement) not divided. Courts consider length of marriage, contribution to acquisition of property, financial condition, earning capacity, child custody impact, and other factors. Property acquired during marriage presumed marital property. Source: Utah Code § 30-3-5."]);
        DB::table('states')->where('state_code', 'VT')->update(['property_division' => "Vermont is equitable distribution state per Vermont Statutes Title 15 § 751. Court divides marital property equitably. Separate property includes property owned before marriage, inherited, and designated as separate. Courts consider length of marriage, contribution to property, financial condition, earning capacity, and ability to acquire property. Equitable means fair but not necessarily equal. Source: Vermont Statutes § 15-751."]);
        DB::table('states')->where('state_code', 'VA')->update(['property_division' => "Virginia is equitable distribution state per Virginia Code § 20-107.3. Court divides marital property equitably. Separate property (before marriage, inherited, gifted, property exchange agreement) not divided. Courts consider duration of marriage, contribution to property acquisition, financial condition, earning capacity, business continuation needs, and tax consequences. Equitable division is fair but not necessarily equal. Source: Virginia Code § 20-107.3."]);
        DB::table('states')->where('state_code', 'WA')->update(['property_division' => "Washington is community property state per Washington RCW 26.16.030. Community property (acquired during marriage) is presumed divided equally unless separate property. Separate property (before marriage, inherited, gifted, by agreement) not divided. Courts may divide unequally for just and equitable reasons. Community property presumption applies to property acquired during marriage. Source: Washington RCW 26.16.030."]);
        DB::table('states')->where('state_code', 'WV')->update(['property_division' => "West Virginia is equitable distribution state per West Virginia Code § 48-2-32. Court divides marital property equitably and justly. Separate property (owned before marriage, inherited, gifted) not divided. Courts consider length of marriage, contribution to property acquisition, financial condition, earning capacity, child custody, and other factors. Marital property is property acquired during marriage. Source: West Virginia Code § 48-2-32."]);
        DB::table('states')->where('state_code', 'WI')->update(['property_division' => "Wisconsin is equitable distribution state with equal division presumption per Wisconsin Statutes § 767.255. Property acquired during marriage presumed marital property. Separate property (before marriage, inherited, gifted, by agreement) not divided. Courts presume equal division of marital property. May divide unequally for substantial reason. Courts consider multiple statutory factors. Source: Wisconsin Statutes § 767.255."]);
        DB::table('states')->where('state_code', 'WY')->update(['property_division' => "Wyoming is equitable distribution state per Wyoming Statutes § 20-2-114. Court divides marital property equitably. Separate property includes property owned before marriage, inherited, gifted, or property exchange agreed to. Courts consider length of marriage, financial condition of parties, contribution to acquisition of property, earning capacity, and other factors. Equitable is fair but not necessarily equal. Source: Wyoming Statutes § 20-2-114."]);
    }

    public function down() { }
}
