<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdateMediationSupportVerifiedBatch5SdThroughWy extends Migration
{
    public function up()
    {
        DB::table('states')->where('state_code', 'SD')->update(['mediation_support' => "South Dakota encourages mediation in family law matters through South Dakota Codified Law § 25-1-40 et seq. Mediation available by agreement or court order. Court may order mediation for contested issues. Not mandatory statewide. Certified mediators available through court system. Parties typically share costs equally. Mediation communications confidential under state law. Court retains authority over unresolved issues. Source: South Dakota Codified Law § 25-1-40."]);
        DB::table('states')->where('state_code', 'TN')->update(['mediation_support' => "Tennessee encourages mediation in family law cases through Tennessee Code § 36-4-121. Mediation available by agreement or court order. Court may order mediation for custody disputes. Not mandatory statewide. Certified family mediators available. Parties typically share costs equally unless agreed otherwise. Mediation communications confidential. Court retains final decision-making authority. Source: Tennessee Code § 36-4-121."]);
        DB::table('states')->where('state_code', 'TX')->update(['mediation_support' => "Texas requires Alternative Dispute Resolution (ADR) including mediation under Texas Family Code § 6.602. Mediation available by agreement or court order for any contested family law issue. Court may order mediation before final hearing. Certified mediators available through court system. Costs typically shared by parties. Mediation communications confidential and privileged. Mandatory good faith participation required. Source: Texas Family Code § 6.602."]);
        DB::table('states')->where('state_code', 'UT')->update(['mediation_support' => "Utah encourages mediation in family law disputes through Utah Rules of Civil Procedure. Mediation available by agreement or court order. Court may order mediation for custody, visitation, or support disputes. Not mandatory statewide. Certified mediators available through court programs. Parties typically share costs equally. Mediation communications confidential. Court retains authority over unresolved issues. Source: Utah Rules of Civil Procedure."]);
        DB::table('states')->where('state_code', 'VT')->update(['mediation_support' => "Vermont encourages mediation in family law matters through Vermont Statutes Title 4 § 4091 et seq. Mediation available by agreement or court order. Court may order mediation for custody and support matters. Not mandatory statewide. Certified mediators available through state program. Parties may share costs equally. Mediation communications confidential and privileged. Source: Vermont Statutes Title 4 § 4091."]);
        DB::table('states')->where('state_code', 'VA')->update(['mediation_support' => "Virginia encourages mediation in family law cases through Virginia Code § 20-121 et seq. Mediation available by agreement or court order. Court may order mediation for custody or support disputes. Not mandatory statewide but encouraged. Certified mediators available. Parties may share costs equally. Mediation communications confidential under state law. Court retains final authority. Source: Virginia Code § 20-121."]);
        DB::table('states')->where('state_code', 'WA')->update(['mediation_support' => "Washington requires mediation for certain family law disputes under Washington Revised Code § 26.09.015. Mediation required for contested custody matters unless waived by court. Court-ordered mediation available. Certified family mediators available. Costs typically shared equally by parties. Mediation communications confidential. Parties must participate in good faith. Source: Washington Revised Code § 26.09.015."]);
        DB::table('states')->where('state_code', 'WV')->update(['mediation_support' => "West Virginia encourages mediation in family law disputes through West Virginia Code § 48-1-1 et seq. Mediation available by agreement or court order. Court may order mediation for contested issues. Not mandatory statewide. Certified mediators available through court system. Parties typically share costs equally. Mediation communications confidential and privileged. Court retains final decision-making authority. Source: West Virginia Code § 48-1-1."]);
        DB::table('states')->where('state_code', 'WI')->update(['mediation_support' => "Wisconsin encourages mediation in family law cases through Wisconsin Statutes § 767.001 et seq. Mediation available by agreement or court order. Court may order mediation for custody, support, or property disputes. Not mandatory statewide but promoted. Certified mediators available through court programs. Parties typically share costs equally. Mediation communications confidential. Source: Wisconsin Statutes § 767.001."]);
        DB::table('states')->where('state_code', 'WY')->update(['mediation_support' => "Wyoming encourages mediation in family law disputes through Wyoming Statutes § 1-36-101 et seq. Mediation available by agreement or court order. Court may order mediation for contested issues. Not mandatory but strongly encouraged. Certified mediators available through court system. Costs shared by parties or determined by mediator agreement. Mediation communications confidential under state law. Source: Wyoming Statutes § 1-36-101."]);
    }

    public function down() { }
}
